/** Cobalt Workshop design reminder: asymmetric, editorial workbench staging—an Electric Cobalt action rail against a quiet deep-ink field. */
import { ArrowRight, ChevronRight, Gamepad2, Layers3, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { Link } from "wouter";
import { ToolCard } from "@/components/ToolCard";
import { categories, featuredTools } from "@/data/tools";
import { gameRegistry } from "@/data/games";
import { useTranslation } from "@/contexts/AppSettingsContext";

export default function Home() {
  const { t, language } = useTranslation();
  return <div>
    <section className="hero-section"><div className="hero-grid site-frame"><div className="hero-copy"><p className="eyebrow text-primary-foreground/70">✦ {t("home.eyebrow")}</p><h1><span>{t("home.titleA")}</span><span>{t("home.titleB")}</span><span className="text-cobalt-light">{t("home.titleC")}</span></h1><p className="hero-description">{t("home.copy")}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/tools" className="hero-primary-cta"><Wrench className="size-4" />{t("home.tools")}<ArrowRight className="size-4" /></Link><Link href="/games" className="hero-secondary-cta"><Gamepad2 className="size-4" />{t("home.games")}</Link></div><div className="hero-stats"><span>{t("home.statTools")}</span><i /><span>{t("home.statGames")}</span><i /><span>{t("home.statFree")}</span><i /><span>{t("home.statPrivacy")}</span></div></div><div className="hero-visual" aria-hidden="true"><img src="https://raw.githubusercontent.com/MdMarufHossen71/Tools-Games/main/assets/tools-games-hero.png" alt="" /><div className="hero-coordinate c1">01 / WORK</div><div className="hero-coordinate c2">02 / PLAY</div></div></div></section>
    <section className="site-frame section-space"><div className="section-heading"><div><p className="eyebrow">01 / TOOLS</p><h2>{t("home.featured")}</h2><p>{t("home.featuredCopy")}</p></div><Link href="/tools" className="text-link">{t("home.viewAll")}<ArrowRight className="size-4" /></Link></div><div className="tool-grid featured-grid">{featuredTools.map((tool) => <ToolCard key={tool.slug} tool={tool} compact />)}</div></section>
    <section className="category-section"><div className="site-frame section-space"><div className="section-heading"><div><p className="eyebrow">02 / SELECT</p><h2>{t("home.categories")}</h2><p>{t("home.categoriesCopy")}</p></div></div><div className="category-trays">{categories.map((category, index) => { const Icon = category.icon; return <Link key={category.id} href={`/tools?category=${category.id}`} className="category-tray"><span className="tray-index">0{index + 1}</span><span className={`tray-icon ${category.tone}`}><Icon className="size-5" /></span><h3>{language === "bn" ? category.bn : category.label}</h3><span>{category.count} <ChevronRight className="inline size-3.5" /></span></Link>; })}</div></div></section>
    <section className="games-feature"><div className="site-frame games-feature-inner"><div className="games-feature-copy"><p className="eyebrow">03 / {t("home.gameKicker")}</p><h2>{t("home.gamesTitle")}</h2><p>{t("home.gamesCopy")}</p><Link href="/games" className="dark-cta"><Gamepad2 className="size-4" />{t("home.games")}<ArrowRight className="size-4" /></Link></div><div className="game-showcase"><img src="https://raw.githubusercontent.com/MdMarufHossen71/Tools-Games/main/assets/tools-games-games.png" alt="" /><div className="floating-game-card"><span><Layers3 className="size-4" /></span><strong>{gameRegistry[0].name}</strong><small>{language === "bn" ? gameRegistry[0].genreBn : gameRegistry[0].genre}</small></div><div className="floating-game-card second"><span><Sparkles className="size-4" /></span><strong>{gameRegistry[2].name}</strong><small>{language === "bn" ? gameRegistry[2].genreBn : gameRegistry[2].genre}</small></div></div></div></section>
    <section className="site-frame section-space"><div className="ai-prompt"><div><p className="eyebrow">04 / {t("home.aiKicker")}</p><h2>{t("home.aiTitle")}</h2><p>{t("home.aiCopy")}</p></div><div className="ai-prompt-action"><span><ShieldCheck className="size-5" /></span><Link href="/ai" className="text-link">{t("home.viewAi")}<ArrowRight className="size-4" /></Link></div><img src="https://raw.githubusercontent.com/MdMarufHossen71/Tools-Games/main/assets/tools-games-ai.png" alt="" /></div></section>
  </div>;
}
