import { useAuth } from "@/_core/hooks/useAuth";
import { useSettings } from "@/contexts/AppSettingsContext";
import { isRelayCandidate, isRelaySignalMessage, parseRelaySignals, relayOnlyConfiguration, serializeRelaySignal, type RelaySignal } from "@/lib/relayOnly";
import { connectFourIndex, winnerFor, type Marker, type MultiplayerSlug } from "@/lib/multiplayerGame";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Copy, LockKeyhole, Send, ShieldCheck, Users } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useLocation } from "wouter";
import "../multiplayer.css";

type LiveMessage = { type: "move" | "sync"; grid: Marker[]; turn: "X" | "O"; gameSlug: MultiplayerSlug };
const emptyTicTacToe = () => Array<Marker>(9).fill("");
const emptyConnectFour = () => Array<Marker>(42).fill("");

export default function MultiplayerRoom({ roomToken }: { roomToken: string }) {
  const { t } = useSettings(); const { user, isAuthenticated, loading } = useAuth(); const [, navigate] = useLocation();
  const [chatBody, setChatBody] = useState(""); const [notice, setNotice] = useState(""); const [connection, setConnection] = useState<"waiting" | "connecting" | "connected" | "error">("waiting");
  const [grid, setGrid] = useState<Marker[]>(emptyTicTacToe); const [turn, setTurn] = useState<"X" | "O">("X"); const pcRef = useRef<RTCPeerConnection | null>(null); const channelRef = useRef<RTCDataChannel | null>(null); const processedSignals = useRef(new Set<string>()); const currentGame = useRef<MultiplayerSlug>("tic-tac-toe");
  const room = trpc.games.getRoom.useQuery({ roomToken }, { enabled: isAuthenticated, refetchInterval: 4_000, retry: false });
  const isMember = Boolean(room.data?.members.some((member) => member.userId === user?.id)); const isHost = room.data?.hostUserId === user?.id;
  const relay = trpc.games.relayCredentials.useQuery(undefined, { enabled: isMember && (room.data?.members.length ?? 0) === 2, retry: false });
  const messages = trpc.games.roomMessages.useQuery({ roomToken }, { enabled: isMember, refetchInterval: 1_800, retry: false });
  const join = trpc.games.joinRoom.useMutation({ onError: () => setNotice(t("games.roomExpired")), onSuccess: () => room.refetch() });
  const heartbeat = trpc.games.heartbeatRoom.useMutation(); const sendMessage = trpc.games.sendRoomMessage.useMutation({ onSuccess: () => { setChatBody(""); messages.refetch(); }, onError: () => setNotice(t("games.roomExpired")) }); const close = trpc.games.closeRoom.useMutation({ onSuccess: () => navigate("/games/lobby"), onError: () => setNotice(t("games.roomExpired")) });
  const displayName = user?.name?.trim().slice(0, 100) || "ToolsHUB Player"; const gameSlug = (room.data?.gameSlug === "connect-four" ? "connect-four" : "tic-tac-toe") as MultiplayerSlug; const myMarker: Marker = isHost ? "X" : "O";
  currentGame.current = gameSlug;
  const sendSignal = useCallback((signal: RelaySignal) => { serializeRelaySignal(signal).forEach((body) => sendMessage.mutate({ roomToken, body })); }, [roomToken, sendMessage]);
  const applyLiveMessage = useCallback((value: unknown) => { const message = value as Partial<LiveMessage>; if (!message || (message.type !== "move" && message.type !== "sync") || (message.gameSlug !== "tic-tac-toe" && message.gameSlug !== "connect-four") || !Array.isArray(message.grid) || message.grid.some((cell) => cell !== "" && cell !== "X" && cell !== "O") || (message.turn !== "X" && message.turn !== "O")) return; const expectedLength = message.gameSlug === "tic-tac-toe" ? 9 : 42; if (message.grid.length !== expectedLength) return; currentGame.current = message.gameSlug; setGrid(message.grid as Marker[]); setTurn(message.turn); }, []);
  const attachChannel = useCallback((channel: RTCDataChannel) => { channelRef.current = channel; channel.onopen = () => { setConnection("connected"); if (isHost) channel.send(JSON.stringify({ type: "sync", grid, turn, gameSlug: currentGame.current } satisfies LiveMessage)); }; channel.onclose = () => setConnection("waiting"); channel.onerror = () => setConnection("error"); channel.onmessage = (event) => { try { applyLiveMessage(JSON.parse(String(event.data))); } catch { /* untrusted payload ignored */ } }; }, [applyLiveMessage, grid, isHost, turn]);
  useEffect(() => { if (!isAuthenticated || !room.data || isMember || join.isPending) return; join.mutate({ roomToken, displayName }); }, [displayName, isAuthenticated, isMember, join, room.data, roomToken]);
  useEffect(() => { if (!isMember) return; heartbeat.mutate({ roomToken }); const id = window.setInterval(() => heartbeat.mutate({ roomToken }), 25_000); return () => window.clearInterval(id); }, [isMember, roomToken]);
  useEffect(() => { if (!isMember || !relay.data || (room.data?.members.length ?? 0) !== 2 || pcRef.current) return; const peer = new RTCPeerConnection(relayOnlyConfiguration(relay.data.iceServers)); pcRef.current = peer; setConnection("connecting");
    peer.onicecandidate = (event) => { if (!event.candidate) return; if (!isRelayCandidate(event.candidate.candidate)) { if (import.meta.env.DEV) console.warn("[ToolsHUB relay verification] rejected non-relay ICE candidate"); return; } if (import.meta.env.DEV) console.info("[ToolsHUB relay verification] outbound candidate type: relay"); sendSignal({ type: "candidate", candidate: event.candidate.toJSON() }); };
    peer.onconnectionstatechange = () => { if (peer.connectionState === "connected") setConnection("connected"); if (["failed", "closed", "disconnected"].includes(peer.connectionState)) setConnection("error"); };
    peer.ondatachannel = (event) => attachChannel(event.channel);
    if (isHost) { const channel = peer.createDataChannel("toolsHubGame", { ordered: true }); attachChannel(channel); peer.createOffer().then((offer) => peer.setLocalDescription(offer)).then(() => { if (peer.localDescription) sendSignal({ type: "offer", sdp: peer.localDescription }); }).catch(() => setConnection("error")); }
    return () => { peer.close(); pcRef.current = null; channelRef.current = null; };
  }, [attachChannel, isHost, isMember, relay.data, room.data?.members.length, sendSignal]);
  useEffect(() => { const peer = pcRef.current; if (!peer || !messages.data || !user) return; const bodies = messages.data.filter((message) => message.userId !== user.id).map((message) => message.body); parseRelaySignals(bodies).forEach(({ id, signal }) => { if (processedSignals.current.has(id)) return; processedSignals.current.add(id); if (signal.type === "candidate") { if (import.meta.env.DEV) console.info("[ToolsHUB relay verification] inbound candidate type: relay"); peer.addIceCandidate(signal.candidate).catch(() => undefined); return; } if (signal.type === "offer" && !isHost) { peer.setRemoteDescription(signal.sdp).then(() => peer.createAnswer()).then((answer) => peer.setLocalDescription(answer)).then(() => { if (peer.localDescription) sendSignal({ type: "answer", sdp: peer.localDescription }); }).catch(() => setConnection("error")); } if (signal.type === "answer" && isHost) peer.setRemoteDescription(signal.sdp).catch(() => setConnection("error")); }); }, [isHost, messages.data, sendSignal, user]);
  useEffect(() => { setGrid(gameSlug === "connect-four" ? emptyConnectFour() : emptyTicTacToe()); setTurn("X"); }, [gameSlug]);
  const winner = useMemo(() => winnerFor(grid, gameSlug), [gameSlug, grid]);
  const makeMove = (position: number) => { if (connection !== "connected" || winner || turn !== myMarker) return; const index = gameSlug === "connect-four" ? connectFourIndex(grid, position) : position; if (index < 0 || grid[index]) return; const next = grid.map((cell, current) => current === index ? myMarker : cell); const nextTurn = myMarker === "X" ? "O" : "X"; setGrid(next); setTurn(nextTurn); channelRef.current?.send(JSON.stringify({ type: "move", grid: next, turn: nextTurn, gameSlug } satisfies LiveMessage)); };
  const resetMatch = () => { if (!isHost) return; const next = gameSlug === "connect-four" ? emptyConnectFour() : emptyTicTacToe(); setGrid(next); setTurn("X"); channelRef.current?.send(JSON.stringify({ type: "sync", grid: next, turn: "X", gameSlug } satisfies LiveMessage)); };
  const visibleMessages = [...(messages.data ?? [])].filter((message) => !isRelaySignalMessage(message.body)).reverse();
  const copyInvite = async () => { try { await navigator.clipboard.writeText(`${window.location.origin}/games/room/${roomToken}`); setNotice(t("blog.copied")); } catch { setNotice("Copy the room URL from your address bar."); } };
  if (!loading && !isAuthenticated) return <main className="site-frame multiplayer-page multiplayer-access"><h1>{t("games.lobbyTitle")}</h1><p>{t("games.saveGuest")}</p><Link href="/profile">{t("auth.signin")}</Link></main>;
  if (room.isLoading || !room.data) return <main className="site-frame multiplayer-page multiplayer-access"><h1>{t("games.connecting")}</h1><p>{room.error ? t("games.roomExpired") : "Loading your private room…"}</p><Link href="/games/lobby"><ArrowLeft size={16}/>{t("games.multiplayer")}</Link></main>;
  return <main className="site-frame multiplayer-page"><Link className="multiplayer-back" href="/games/lobby"><ArrowLeft size={16}/>{t("games.multiplayer")}</Link><section className="room-top"><div><p className="eyebrow">{gameSlug === "connect-four" ? "CONNECT FOUR" : "TIC TAC TOE"}</p><h1>{room.data.displayName}'s room</h1><p className="relay-badge"><ShieldCheck size={16}/>{t("games.privacy")}</p></div><div className="room-actions"><button onClick={copyInvite}><Copy size={16}/>{t("games.invite")}</button>{isHost && <button className="danger" onClick={() => close.mutate({ roomToken })}>{t("games.leave")}</button>}</div></section><section className="room-layout"><div className="live-game"><div className="live-status"><span className={`connection-dot ${connection}`}/>{connection === "connected" ? t("games.online") : connection === "error" ? t("games.relayUnavailable") : t("games.connecting")}<small>{room.data.members.length}/2</small></div><div className={`online-board ${gameSlug}`}>{grid.map((marker, index) => <button key={index} disabled={connection !== "connected" || Boolean(winner) || turn !== myMarker} onClick={() => makeMove(gameSlug === "connect-four" ? index % 7 : index)}>{marker && <span className={marker === "X" ? "x" : "o"}>{marker}</span>}</button>)}</div><p className="game-turn">{winner ? `${winner} wins` : connection === "connected" ? turn === myMarker ? "Your turn" : "Opponent's turn" : "Waiting for a relay-only connection"}</p>{isHost && <button className="match-reset" onClick={resetMatch}>New match</button>}</div><aside className="room-side"><div className="room-members"><h2><Users size={17}/>{t("games.online")}</h2>{room.data.members.map((member) => <p key={member.userId}><span className="presence"/>{member.displayName}{member.userId === user?.id ? " (you)" : ""}</p>)}</div><div className="room-chat"><h2>{t("games.chat")}</h2><div className="chat-log">{visibleMessages.map((message) => <p key={message.id} className={message.userId === user?.id ? "mine" : ""}>{message.body}</p>)}</div><form onSubmit={(event) => { event.preventDefault(); if (chatBody.trim()) sendMessage.mutate({ roomToken, body: chatBody.trim() }); }}><input value={chatBody} maxLength={500} onChange={(event) => setChatBody(event.target.value)} placeholder={t("games.chat")} /><button aria-label={t("games.send")}><Send size={16}/></button></form></div></aside></section>{notice && <p className="multiplayer-notice" role="status">{notice}</p>}</main>;
}
