import { useAuth } from "@/_core/hooks/useAuth";
import { useSettings } from "@/contexts/AppSettingsContext";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { FileKey, Files, Link2, LockKeyhole, NotebookPen, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { QRCodeSVG } from "qrcode.react";
import { buildTrackedUrl } from "@/lib/shortLinkUtm";
import { generateSecurePassword } from "@/lib/passwordGenerator";
import "../my-data.css";

type DataSection = "files" | "clipboard" | "notes" | "vault" | "links";

function toDataUrl(file: File) {
  return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("file")); reader.readAsDataURL(file); });
}

async function encryptVaultValue(value: string, password: string) {
  const encoder = new TextEncoder(); const bytes = crypto.getRandomValues(new Uint8Array(16)); const ivBytes = crypto.getRandomValues(new Uint8Array(12));
  const material = await crypto.subtle.importKey("raw", encoder.encode(password), "PBKDF2", false, ["deriveKey"]);
  const key = await crypto.subtle.deriveKey({ name: "PBKDF2", salt: bytes, iterations: 180000, hash: "SHA-256" }, material, { name: "AES-GCM", length: 256 }, false, ["encrypt"]);
  const encrypted = await crypto.subtle.encrypt({ name: "AES-GCM", iv: ivBytes }, key, encoder.encode(value));
  const encode = (data: Uint8Array) => btoa(Array.from(data).map((byte) => String.fromCharCode(byte)).join(""));
  return { ciphertext: encode(new Uint8Array(encrypted)), iv: encode(ivBytes), salt: encode(bytes), cryptoVersion: "aes-gcm-pbkdf2-v1" };
}

export default function MyData() {
  const { t } = useSettings(); const { isAuthenticated } = useAuth(); const utils = trpc.useUtils();
  const [section, setSection] = useState<DataSection>("files"); const [clipboard, setClipboard] = useState(""); const [noteId, setNoteId] = useState<number | null>(null); const [noteTitle, setNoteTitle] = useState(""); const [noteBody, setNoteBody] = useState(""); const [vaultTitle, setVaultTitle] = useState(""); const [vaultValue, setVaultValue] = useState(""); const [vaultPassword, setVaultPassword] = useState(""); const [targetUrl, setTargetUrl] = useState(""); const [linkAlias, setLinkAlias] = useState(""); const [linkPassword, setLinkPassword] = useState(""); const [linkExpiry, setLinkExpiry] = useState(""); const [linkLimit, setLinkLimit] = useState(""); const [utmSource, setUtmSource] = useState(""); const [utmMedium, setUtmMedium] = useState(""); const [utmCampaign, setUtmCampaign] = useState(""); const [utmTerm, setUtmTerm] = useState(""); const [utmContent, setUtmContent] = useState(""); const [createdLink, setCreatedLink] = useState<string | null>(null); const [filePassword, setFilePassword] = useState(""); const [fileExpiry, setFileExpiry] = useState(""); const [fileLimit, setFileLimit] = useState(""); const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const files = trpc.fileShare.list.useQuery(undefined, { enabled: isAuthenticated }); const clips = trpc.clipboard.list.useQuery(undefined, { enabled: isAuthenticated }); const notes = trpc.notes.list.useQuery(undefined, { enabled: isAuthenticated }); const noteHistory = trpc.notes.history.useQuery({ id: noteId ?? 1 }, { enabled: isAuthenticated && noteId !== null }); const vault = trpc.vault.list.useQuery(undefined, { enabled: isAuthenticated }); const links = trpc.shortLinks.list.useQuery(undefined, { enabled: isAuthenticated });
  const addClip = trpc.clipboard.add.useMutation({ onSuccess: () => { setClipboard(""); utils.clipboard.list.invalidate(); } }); const removeClip = trpc.clipboard.delete.useMutation({ onSuccess: () => utils.clipboard.list.invalidate() });
  const saveNote = trpc.notes.save.useMutation({ onSuccess: () => { setNoteId(null); setNoteTitle(""); setNoteBody(""); utils.notes.list.invalidate(); noteHistory.refetch(); } }); const removeNote = trpc.notes.delete.useMutation({ onSuccess: () => { setNoteId(null); setNoteTitle(""); setNoteBody(""); utils.notes.list.invalidate(); } });
  const saveVault = trpc.vault.save.useMutation({ onSuccess: () => { setVaultTitle(""); setVaultValue(""); setVaultPassword(""); utils.vault.list.invalidate(); } }); const removeVault = trpc.vault.delete.useMutation({ onSuccess: () => utils.vault.list.invalidate() });
  const makeLink = trpc.shortLinks.create.useMutation({ onSuccess: ({ path }) => { const url = `${location.origin}${path}`; navigator.clipboard?.writeText(url).catch(() => undefined); setCreatedLink(url); setTargetUrl(""); setLinkAlias(""); setLinkPassword(""); setLinkExpiry(""); setLinkLimit(""); utils.shortLinks.list.invalidate(); toast.success(t("data.shareReady")); } });
  const makeFile = trpc.fileShare.create.useMutation({ onSuccess: ({ sharePath }) => { navigator.clipboard?.writeText(`${location.origin}${sharePath}`).catch(() => undefined); setSelectedFile(null); setFilePassword(""); setFileExpiry(""); setFileLimit(""); utils.fileShare.list.invalidate(); toast.success(t("data.shareReady")); } });
  const deleteLink = trpc.shortLinks.delete.useMutation({ onSuccess: () => utils.shortLinks.list.invalidate() });
  const nav = useMemo(() => [{ id: "files" as const, icon: Files, label: t("data.files") }, { id: "clipboard" as const, icon: FileKey, label: t("data.clipboard") }, { id: "notes" as const, icon: NotebookPen, label: t("data.notes") }, { id: "vault" as const, icon: LockKeyhole, label: t("data.vault") }, { id: "links" as const, icon: Link2, label: t("data.links") }], [t]);
  if (!isAuthenticated) return <main className="container data-page"><section className="data-signin"><ShieldCheck /><h1>{t("data.title")}</h1><p>{t("profile.signinCopy")}</p><a href="/profile"><Button>{t("profile.secureSignin")}</Button></a></section></main>;
  return <main className="container data-page"><header className="data-header"><div><span className="eyebrow"><ShieldCheck size={15} /> {t("data.private")}</span><h1>{t("data.title")}</h1><p>{t("data.copy")}</p></div><aside><LockKeyhole size={18} /> {t("data.sensitive")}</aside></header><div className="data-layout"><nav className="data-tabs">{nav.map(({ id, icon: Icon, label }) => <button className={section === id ? "active" : ""} onClick={() => setSection(id)} key={id}><Icon size={17} />{label}</button>)}</nav><section className="data-panel">
    {section === "files" && <><div className="panel-head"><h2>{t("data.files")}</h2><label className="file-button"><Plus size={16}/>{t("data.create")}<input type="file" onChange={(event) => setSelectedFile(event.target.files?.[0] ?? null)} /></label></div>{selectedFile && <div className="data-form"><span>{selectedFile.name}</span><Input aria-label={t("data.passwordOptional")} value={filePassword} onChange={(event) => setFilePassword(event.target.value)} placeholder={t("data.passwordOptional")} /><Input aria-label={t("data.expiry")} type="date" value={fileExpiry} onChange={(event) => setFileExpiry(event.target.value)} /><Input aria-label={t("data.maxDownloads")} type="number" min="1" value={fileLimit} onChange={(event) => setFileLimit(event.target.value)} placeholder={t("data.maxDownloads")} /><Button disabled={makeFile.isPending} onClick={async () => { try { makeFile.mutate({ dataUrl: await toDataUrl(selectedFile), filename: selectedFile.name, password: filePassword || null, expiresAt: fileExpiry ? new Date(`${fileExpiry}T23:59:59.999Z`) : null, maxDownloads: fileLimit ? Number(fileLimit) : null }); } catch { toast.error(t("tool.downloadFailed")); } }}>{t("admin.save")}</Button></div>}{files.data?.length ? <div className="data-list">{files.data.map((item) => <article key={item.id}><Files size={18}/><div><strong>{item.name}</strong><small>{item.downloadCount} / {item.maxDownloads ?? "∞"}</small></div><span>{new Date(item.createdAt).toLocaleDateString()}</span></article>)}</div> : <p className="data-empty">{t("data.empty")}</p>}</>}
    {section === "clipboard" && <><div className="panel-head"><h2>{t("data.clipboard")}</h2></div><div className="data-form"><Textarea value={clipboard} onChange={(event) => setClipboard(event.target.value)} aria-label={t("data.clipboard")} /><Button disabled={!clipboard || addClip.isPending} onClick={() => addClip.mutate({ content: clipboard, category: "text", expiresAt: null })}><Plus size={16}/>{t("data.create")}</Button></div><div className="data-list">{clips.data?.map((item) => <article key={item.id}><FileKey size={18}/><p>{item.content}</p><Button variant="ghost" size="icon" onClick={() => removeClip.mutate({ id: item.id })}><Trash2 size={16}/></Button></article>)}</div></>}
    {section === "notes" && <><div className="panel-head"><h2>{t("data.notes")}</h2><Button type="button" variant="outline" onClick={() => { setNoteId(null); setNoteTitle(""); setNoteBody(""); }}>{t("admin.new")}</Button></div><div className="data-form"><Input value={noteTitle} onChange={(event) => setNoteTitle(event.target.value)} placeholder={t("data.noteTitle")} /><Textarea value={noteBody} onChange={(event) => setNoteBody(event.target.value)} placeholder={t("data.noteBody")} /><Button disabled={!noteTitle || saveNote.isPending} onClick={() => saveNote.mutate({ ...(noteId ? { id: noteId } : {}), title: noteTitle, content: noteBody, tags: [], color: "violet", isPinned: false, folderId: null })}>{t("admin.save")}</Button></div>{noteId !== null && noteHistory.data?.length ? <div className="data-list">{noteHistory.data.map((item) => <article key={item.id}><NotebookPen size={18}/><div><strong>v{item.version}</strong><small>{item.title}</small></div><span>{new Date(item.createdAt).toLocaleDateString()}</span></article>)}</div> : null}<div className="data-list">{notes.data?.map((item) => <article key={item.id}><NotebookPen size={18}/><div><strong>{item.title}</strong><small>{item.content?.slice(0, 100)}</small></div><Button variant="ghost" size="icon" aria-label={t("admin.edit")} onClick={() => { setNoteId(item.id); setNoteTitle(item.title); setNoteBody(item.content ?? ""); }}><NotebookPen size={16}/></Button><Button variant="ghost" size="icon" onClick={() => removeNote.mutate({ id: item.id })}><Trash2 size={16}/></Button></article>)}</div></>}
    {section === "vault" && <><div className="panel-head"><h2>{t("data.vault")}</h2><small>{t("data.clientEncrypted")}</small></div><div className="data-form"><Input value={vaultTitle} onChange={(event) => setVaultTitle(event.target.value)} placeholder={t("data.noteTitle")} /><div className="flex gap-2"><Input type="password" value={vaultValue} onChange={(event) => setVaultValue(event.target.value)} placeholder={t("data.vault")} /><Button type="button" variant="outline" onClick={() => setVaultValue(generateSecurePassword())}>{t("tool.generate")}</Button></div><Input type="password" value={vaultPassword} onChange={(event) => setVaultPassword(event.target.value)} placeholder={t("data.passwordOptional")} /><Button disabled={!vaultTitle || !vaultValue || !vaultPassword || saveVault.isPending} onClick={async () => { try { saveVault.mutate({ title: vaultTitle, kind: "secure_note", ...(await encryptVaultValue(vaultValue, vaultPassword)) }); } catch { toast.error(t("tool.copyFailed")); } }}>{t("admin.save")}</Button></div><div className="data-list">{vault.data?.map((item) => <article key={item.id}><LockKeyhole size={18}/><div><strong>{item.title}</strong><small>{item.kind}</small></div><Button variant="ghost" size="icon" onClick={() => removeVault.mutate({ id: item.id })}><Trash2 size={16}/></Button></article>)}</div></>}
    {section === "links" && <><div className="panel-head"><h2>{t("data.links")}</h2></div><div className="data-form"><Input value={targetUrl} onChange={(event) => setTargetUrl(event.target.value)} placeholder="https://" inputMode="url" /><Input aria-label={t("data.links")} value={linkAlias} onChange={(event) => setLinkAlias(event.target.value)} placeholder={t("data.links")} /><Input aria-label={t("data.passwordOptional")} value={linkPassword} onChange={(event) => setLinkPassword(event.target.value)} placeholder={t("data.passwordOptional")} type="password" /><Input aria-label={t("data.expiry")} type="date" value={linkExpiry} onChange={(event) => setLinkExpiry(event.target.value)} /><Input aria-label={t("data.maxDownloads")} type="number" min="1" value={linkLimit} onChange={(event) => setLinkLimit(event.target.value)} placeholder={t("data.maxDownloads")} /><Input aria-label={t("data.links")} value={utmSource} onChange={(event) => setUtmSource(event.target.value)} placeholder="utm source" /><Input aria-label={t("data.links")} value={utmMedium} onChange={(event) => setUtmMedium(event.target.value)} placeholder="utm medium" /><Input aria-label={t("data.links")} value={utmCampaign} onChange={(event) => setUtmCampaign(event.target.value)} placeholder="utm campaign" /><Input aria-label={t("data.links")} value={utmTerm} onChange={(event) => setUtmTerm(event.target.value)} placeholder="utm term" /><Input aria-label={t("data.links")} value={utmContent} onChange={(event) => setUtmContent(event.target.value)} placeholder="utm content" /><Button disabled={!targetUrl || makeLink.isPending} onClick={() => { try { makeLink.mutate({ targetUrl: buildTrackedUrl(targetUrl, { source: utmSource, medium: utmMedium, campaign: utmCampaign, term: utmTerm, content: utmContent }), alias: linkAlias || undefined, password: linkPassword || null, expiresAt: linkExpiry ? new Date(`${linkExpiry}T23:59:59.999Z`) : null, clickLimit: linkLimit ? Number(linkLimit) : null }); } catch { toast.error(t("tool.invalid")); } }}><Plus size={16}/>{t("data.create")}</Button></div>{createdLink && <div className="data-form inline"><a href={createdLink}>{createdLink}</a><QRCodeSVG value={createdLink} size={112} level="M" includeMargin /></div>}<div className="data-list">{links.data?.map((item) => <article key={item.id}><Link2 size={18}/><div><strong>/{item.alias}</strong><small>{item.clickCount}</small></div><Button variant="ghost" size="icon" onClick={() => { navigator.clipboard?.writeText(`${location.origin}/s/${item.alias}`).catch(() => undefined); }}><Link2 size={16}/></Button><Button variant="ghost" size="icon" onClick={() => deleteLink.mutate({ id: item.id })}><Trash2 size={16}/></Button></article>)}</div></>}
  </section></div></main>;
}
