import { useSettings } from "@/contexts/AppSettingsContext";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { sessionToResume } from "@/lib/gameSession";
import { Expand, Pause, RotateCcw, Volume2, VolumeX } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import "../games-fixes.css";

type FrameProps = { title: string; score?: number; paused?: boolean; setPaused?: (value: boolean) => void; onReset: () => void; children: React.ReactNode; footer?: React.ReactNode };
type SessionProps = { gameSlug: string; state: Record<string, unknown>; restore: (state: Record<string, unknown>) => void };
function GameSessionBridge({ gameSlug, state, restore }: SessionProps) {
  const { isAuthenticated } = useAuth();
  const progress = trpc.games.getProgress.useQuery({ gameSlug }, { enabled: isAuthenticated });
  const saveSession = trpc.games.saveSession.useMutation();
  const localActionAt = useRef(0); const initial = useRef(JSON.stringify(state)); const restored = useRef(false); const restoreRef = useRef(restore); restoreRef.current = restore;
  const serialized = JSON.stringify(state);
  useEffect(() => { if (serialized !== initial.current) localActionAt.current = Date.now(); }, [serialized]);
  useEffect(() => { if (!isAuthenticated || !progress.isFetched || restored.current) return; const remote = sessionToResume((progress.data?.resources as { session?: unknown } | null)?.session, localActionAt.current); if (remote) { restoreRef.current(remote.state); initial.current = JSON.stringify(remote.state); } restored.current = true; }, [isAuthenticated, progress.data?.resources, progress.isFetched]);
  useEffect(() => { if (!isAuthenticated || !restored.current || !localActionAt.current) return; const timer = window.setTimeout(() => saveSession.mutate({ gameSlug, session: { version: 1, savedAt: localActionAt.current, state }, deviceType: /mobile/i.test(navigator.userAgent) ? "mobile" : "desktop" }), 650); return () => window.clearTimeout(timer); }, [gameSlug, isAuthenticated, serialized]);
  return null;
}
function GameFrame({ title, score = 0, paused = false, setPaused, onReset, children, footer }: FrameProps) {
  const { t } = useSettings(); const { isAuthenticated } = useAuth(); const ref = useRef<HTMLDivElement>(null); const [sound, setSound] = useState(true); const [saveNotice, setSaveNotice] = useState<"guest" | "error" | null>(null); const gameSlug = title.toLowerCase().replace(/\s+/g, "-"); const submittedScore = useRef(-1); const leaderboard = trpc.games.leaderboard.useQuery({ gameSlug }); const progress = trpc.games.getProgress.useQuery({ gameSlug }, { enabled: isAuthenticated }); const submitScore = trpc.games.submitScore.useMutation({ onSuccess: () => { setSaveNotice(null); leaderboard.refetch(); progress.refetch(); }, onError: () => setSaveNotice("error") });
  useEffect(() => { if (score < 1 || score === submittedScore.current) return; if (!isAuthenticated) { setSaveNotice("guest"); return; } submittedScore.current = score; submitScore.mutate({ gameSlug, score, deviceType: typeof navigator === "undefined" ? "browser" : /mobile/i.test(navigator.userAgent) ? "mobile" : "desktop" }); }, [gameSlug, isAuthenticated, score]);
  const streak = (progress.data?.resources as { gameStreak?: { current?: number } } | null)?.gameStreak?.current;
  return <><section className="game-frame" ref={ref}><header className="game-frame-head"><div><span className="game-label">{t("games.score")}</span><strong>{score}</strong></div><h2>{title}</h2><div className="game-frame-actions">{setPaused && <button aria-label={paused ? t("games.resume") : t("games.pause")} onClick={() => setPaused(!paused)}>{paused ? <span className="play-symbol">▶</span> : <Pause size={16}/>}</button>}<button aria-label={t("games.sound")} className={!sound ? "muted" : ""} onClick={() => setSound(!sound)}>{sound ? <Volume2 size={16}/> : <VolumeX size={16}/>}</button><button aria-label={t("tool.reset")} onClick={onReset}><RotateCcw size={16}/></button><button aria-label={t("games.fullscreen")} onClick={() => ref.current?.requestFullscreen?.()}><Expand size={16}/></button></div></header><div className={`game-frame-content${paused ? " is-paused" : ""}`}>{children}{paused && <div className="game-pause-overlay">{t("games.pause")}</div>}</div>{footer && <footer className="game-frame-foot">{footer}</footer>}</section><aside className="game-leaderboard" aria-label={t("games.leaderboard")}><h3>{t("games.leaderboard")}</h3><div>{leaderboard.data?.entries.length ? leaderboard.data.entries.slice(0, 3).map((entry) => <span key={entry.userId}>#{entry.rank} · {entry.score}</span>) : <span>—</span>}{leaderboard.data?.you && <strong>#{leaderboard.data.you.rank} · {leaderboard.data.you.score}</strong>}{isAuthenticated && progress.data && <strong>{t("games.best")}: {progress.data.bestScore}</strong>}{isAuthenticated && typeof streak === "number" && <strong>{t("profile.streak")}: {streak}</strong>}</div></aside>{saveNotice && <p className="game-save-notice" role="status">{t(saveNotice === "guest" ? "games.saveGuest" : "games.saveFailed")}</p>}</>;
}

const EN_WORDS = ["GRAPE", "CRANE", "BLOOM", "SNAKE", "FRAME"];
const BN_WORDS = ["বাংলা", "ছবিতে", "সকালে", "কলমটি", "মেঘলা"];
function WordleGame() {
  const { t } = useSettings(); const [mode, setMode] = useState<"en" | "bn">("en"); const [answer, setAnswer] = useState(EN_WORDS[0]); const [guess, setGuess] = useState(""); const [rows, setRows] = useState<string[]>([]); const [notice, setNotice] = useState("");
  const letters = Array.from(guess); const answerLetters = Array.from(answer); const length = answerLetters.length;
  const reset = (nextMode = mode) => { const list = nextMode === "en" ? EN_WORDS : BN_WORDS; setMode(nextMode); setAnswer(list[Math.floor(Math.random() * list.length)]); setGuess(""); setRows([]); setNotice(""); };
  const enter = () => { if (letters.length !== length) { setNotice(`Use ${length} letters`); return; } const value = guess.toUpperCase(); setRows((old) => [...old, value]); setGuess(""); if (value === answer.toUpperCase()) setNotice("You solved it!"); else if (rows.length === 5) setNotice(`Answer: ${answer}`); };
  useEffect(() => { const key = (event: KeyboardEvent) => { if (mode !== "en" || rows.length >= 6 || notice) return; if (/^[a-zA-Z]$/.test(event.key) && letters.length < length) setGuess((old) => old + event.key.toUpperCase()); if (event.key === "Backspace") setGuess((old) => Array.from(old).slice(0, -1).join("")); if (event.key === "Enter") enter(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  const score = rows.some((row) => row === answer.toUpperCase()) ? Math.max(100, 700 - rows.length * 80) : 0;
  const mark = (letter: string, index: number) => letter === answerLetters[index]?.toUpperCase() ? "correct" : answer.toUpperCase().includes(letter) ? "present" : "absent";
  return <GameFrame title="Wordle" score={score} onReset={() => reset()} footer={<span>{t("games.instructions")}: Find the hidden word in six tries.</span>}><GameSessionBridge gameSlug="wordle" state={{ mode, answer, guess, rows, notice }} restore={(state) => { const nextMode = state.mode === "bn" ? "bn" : "en"; const words = nextMode === "bn" ? BN_WORDS : EN_WORDS; setMode(nextMode); setAnswer(typeof state.answer === "string" && words.includes(state.answer) ? state.answer : words[0]); setGuess(typeof state.guess === "string" ? state.guess.slice(0, 8) : ""); setRows(Array.isArray(state.rows) ? state.rows.filter((item): item is string => typeof item === "string").slice(0, 6) : []); setNotice(typeof state.notice === "string" ? state.notice.slice(0, 120) : ""); }}/><div className="wordle-game"><div className="wordle-mode"><span>{t("games.wordleMode")}</span><button className={mode === "en" ? "selected" : ""} onClick={() => reset("en")}>{t("games.english")}</button><button className={mode === "bn" ? "selected" : ""} onClick={() => reset("bn")}>{t("games.bangla")}</button></div><div className="wordle-grid">{Array.from({ length: 6 }).map((_, row) => <div key={row} className="wordle-row">{Array.from({ length }).map((__, column) => { const letter = Array.from(rows[row] ?? (row === rows.length ? guess : ""))[column] ?? ""; return <span className={rows[row] ? mark(letter.toUpperCase(), column) : ""} key={column}>{letter}</span>; })}</div>)}</div><div className="wordle-keyboard">{(mode === "en" ? "QWERTYUIOPASDFGHJKLZXCVBNM".split("") : ["অ","আ","ই","উ","এ","ক","খ","গ","ঘ","চ","জ","ট","ড","ত","দ","ন","প","ব","ম","ল","শ","স","া","ে","ো","ং"]).map((letter) => <button key={letter} onClick={() => letters.length < length && setGuess((old) => old + letter)}>{letter}</button>)}<button onClick={() => setGuess((old) => Array.from(old).slice(0,-1).join(""))}>⌫</button><button onClick={enter}>↵</button></div>{notice && <p className="game-notice">{notice}</p>}</div></GameFrame>;
}

type Tile = number[];
const newBoard = (): Tile => { const board = Array(16).fill(0); board[Math.floor(Math.random()*16)] = 2; board[Math.floor(Math.random()*16)] ||= 2; return board; };
function Game2048() { const [board, setBoard] = useState<Tile>(newBoard); const [score, setScore] = useState(0); const [paused, setPaused] = useState(false); const reset = () => { setBoard(newBoard()); setScore(0); };
  const move = (direction: "left"|"right"|"up"|"down") => { if (paused) return; const source = [...board]; const line = (items: number[]) => { const compact = items.filter(Boolean); const next: number[] = []; let gained=0; for(let index=0; index<compact.length; index++){ if(compact[index] === compact[index+1]) { next.push(compact[index]*2); gained+=compact[index]*2; index++; } else next.push(compact[index]); } return { values: [...next, ...Array(4-next.length).fill(0)], gained }; }; let gained=0; const result = Array(16).fill(0); for(let index=0;index<4;index++){ const positions = direction === "left" || direction === "right" ? [index*4,index*4+1,index*4+2,index*4+3] : [index,index+4,index+8,index+12]; const reversed = direction === "right" || direction === "down"; const values = positions.map((position)=>source[position]); if(reversed) values.reverse(); const joined=line(values); gained += joined.gained; const output=reversed?[...joined.values].reverse():joined.values; positions.forEach((position, inner)=>result[position]=output[inner]); } if (result.some((value,index)=>value!==source[index])) { const empties=result.map((v,i)=>v===0?i:-1).filter((i)=>i>=0); result[empties[Math.floor(Math.random()*empties.length)]]=Math.random()>.85?4:2; setBoard(result);setScore((old)=>old+gained); }};
  useEffect(()=>{ const listener=(event:KeyboardEvent)=>{ const map:Record<string, () => void> = { ArrowLeft:()=>move("left"),ArrowRight:()=>move("right"),ArrowUp:()=>move("up"),ArrowDown:()=>move("down")}; if(map[event.key]) {event.preventDefault();map[event.key]();}};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener);});
  return <GameFrame title="2048" score={score} paused={paused} setPaused={setPaused} onReset={reset} footer={<div className="direction-pad"><button onClick={()=>move("up")}>↑</button><span/><button onClick={()=>move("left")}>←</button><button onClick={()=>move("down")}>↓</button><button onClick={()=>move("right")}>→</button></div>}><GameSessionBridge gameSlug="2048" state={{ board, score, paused }} restore={(state) => { if (Array.isArray(state.board) && state.board.length === 16 && state.board.every((value) => typeof value === "number" && Number.isFinite(value))) setBoard(state.board as Tile); if (typeof state.score === "number" && state.score >= 0) setScore(state.score); setPaused(Boolean(state.paused)); }}/><div className="grid-2048">{board.map((tile,index)=><span className={`tile tile-${tile}`} key={index}>{tile||""}</span>)}</div></GameFrame>;
}

function SnakeGame() { const canvasRef=useRef<HTMLCanvasElement>(null); const direction=useRef({x:1,y:0}); const [snake,setSnake]=useState([{x:9,y:9},{x:8,y:9},{x:7,y:9}]); const [food,setFood]=useState({x:14,y:6}); const [score,setScore]=useState(0); const [paused,setPaused]=useState(false); const reset=()=>{setSnake([{x:9,y:9},{x:8,y:9},{x:7,y:9}]);setFood({x:14,y:6});setScore(0);direction.current={x:1,y:0};};
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{const map:Record<string,{x:number,y:number}>={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0}};if(map[event.key]&&!(map[event.key].x===-direction.current.x&&map[event.key].y===-direction.current.y)){direction.current=map[event.key];}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);},[]);
  useEffect(()=>{if(paused)return;const timer=window.setInterval(()=>setSnake(old=>{const head={x:(old[0].x+direction.current.x+20)%20,y:(old[0].y+direction.current.y+20)%20};if(old.some(p=>p.x===head.x&&p.y===head.y)){setTimeout(reset,0);return old;}const next=[head,...old];if(head.x===food.x&&head.y===food.y){setScore(s=>s+10);setFood({x:Math.floor(Math.random()*20),y:Math.floor(Math.random()*20)});return next;}return next.slice(0,-1);}),125);return()=>clearInterval(timer);},[food,paused]);
  useEffect(()=>{const frame=window.requestAnimationFrame(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.fillStyle="#12152d";ctx.fillRect(0,0,400,400);ctx.strokeStyle="rgba(255,255,255,.06)";for(let i=0;i<=20;i++){ctx.beginPath();ctx.moveTo(i*20,0);ctx.lineTo(i*20,400);ctx.moveTo(0,i*20);ctx.lineTo(400,i*20);ctx.stroke();}ctx.fillStyle="#f6be61";ctx.beginPath();ctx.arc(food.x*20+10,food.y*20+10,7,0,Math.PI*2);ctx.fill();ctx.fillStyle="#74e0ba";snake.forEach((piece,index)=>{ctx.globalAlpha=index?0.8:1;ctx.fillRect(piece.x*20+2,piece.y*20+2,16,16)});ctx.globalAlpha=1;});return()=>window.cancelAnimationFrame(frame);},[snake,food]);
  const turn=(x:number,y:number)=>{if(x!==-direction.current.x||y!==-direction.current.y)direction.current={x,y};}; return <GameFrame title="Snake" score={score} paused={paused} setPaused={setPaused} onReset={reset} footer={<div className="direction-pad"><button onClick={()=>turn(0,-1)}>↑</button><span/><button onClick={()=>turn(-1,0)}>←</button><button onClick={()=>turn(0,1)}>↓</button><button onClick={()=>turn(1,0)}>→</button></div>}><GameSessionBridge gameSlug="snake" state={{ snake, food, score, paused, direction: direction.current }} restore={(state) => { const points = (value: unknown) => Array.isArray(value) && value.length > 1 && value.length <= 100 && value.every((item) => item && typeof item === "object" && typeof (item as { x?: unknown }).x === "number" && typeof (item as { y?: unknown }).y === "number") ? value as { x: number; y: number }[] : null; const savedSnake = points(state.snake); const savedFood = points([state.food])?.[0]; if (savedSnake) setSnake(savedSnake); if (savedFood) setFood(savedFood); if (typeof state.score === "number" && state.score >= 0) setScore(state.score); setPaused(Boolean(state.paused)); const nextDirection = state.direction as { x?: unknown; y?: unknown }; if (typeof nextDirection?.x === "number" && typeof nextDirection?.y === "number") direction.current = { x: nextDirection.x, y: nextDirection.y }; }}/><canvas className="snake-canvas" ref={canvasRef} width="400" height="400"/></GameFrame>;
}

function TetrisGame(){ const [blocks,setBlocks]=useState<{x:number,y:number}[]>([{x:4,y:0},{x:5,y:0},{x:4,y:1},{x:5,y:1}]);const [settled,setSettled]=useState<{x:number,y:number}[]>([]);const [score,setScore]=useState(0);const [paused,setPaused]=useState(false);const reset=()=>{setBlocks([{x:4,y:0},{x:5,y:0},{x:4,y:1},{x:5,y:1}]);setSettled([]);setScore(0)};const shift=(distance:number)=>setBlocks(old=>old.every(b=>distance < 0 ? b.x>0 : b.x<9)?old.map(b=>({...b,x:b.x+distance})):old);const step=()=>{if(paused)return;const blocked=blocks.some(b=>b.y===15||settled.some(s=>s.x===b.x&&s.y===b.y+1));if(blocked){setSettled(old=>[...old,...blocks]);setBlocks([{x:Math.floor(Math.random()*7)+1,y:0},{x:Math.floor(Math.random()*7)+1,y:1},{x:Math.floor(Math.random()*7)+1,y:2},{x:Math.floor(Math.random()*7)+1,y:3}]);setScore(v=>v+10)}else setBlocks(old=>old.map(b=>({...b,y:b.y+1})));};useEffect(()=>{const timer=window.setInterval(step,480);return()=>clearInterval(timer)},[blocks,settled,paused]);useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==="ArrowLeft")shift(-1);if(e.key==="ArrowRight")shift(1);if(e.key==="ArrowDown")step();};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener)});const occupied=(x:number,y:number)=>blocks.some(b=>b.x===x&&b.y===y)?"active":settled.some(b=>b.x===x&&b.y===y)?"locked":"";const restorePoints=(value:unknown)=>Array.isArray(value)&&value.length<=160&&value.every(item=>item&&typeof item==="object"&&typeof (item as {x?:unknown}).x==="number"&&typeof (item as {y?:unknown}).y==="number")?value as {x:number;y:number}[]:null;return <GameFrame title="Tetris" score={score} paused={paused} setPaused={setPaused} onReset={reset} footer={<div className="direction-pad"><span/><span/><button onClick={()=>shift(-1)}>←</button><button onClick={step}>↓</button><button onClick={()=>shift(1)}>→</button></div>}><GameSessionBridge gameSlug="tetris" state={{ blocks, settled, score, paused }} restore={(state)=>{const nextBlocks=restorePoints(state.blocks),nextSettled=restorePoints(state.settled);if(nextBlocks?.length)setBlocks(nextBlocks);if(nextSettled)setSettled(nextSettled);if(typeof state.score==="number"&&state.score>=0)setScore(state.score);setPaused(Boolean(state.paused));}}/><div className="tetris-board">{Array.from({length:160}).map((_,index)=><span key={index} className={occupied(index%10,Math.floor(index/10))}/>)}</div></GameFrame>}

function MemoryGame(){const symbols=["●","◆","▲","■","✦","✚"];const [cards,setCards]=useState(()=>[...symbols,...symbols].sort(()=>Math.random()-.5));const [open,setOpen]=useState<number[]>([]);const [solved,setSolved]=useState<number[]>([]);const [moves,setMoves]=useState(0);const [paused,setPaused]=useState(false);const choose=(index:number)=>{if(paused||open.includes(index)||solved.includes(index)||open.length===2)return;const next=[...open,index];setOpen(next);if(next.length===2){setMoves(m=>m+1);if(cards[next[0]]===cards[next[1]]){setSolved(old=>[...old,...next]);setOpen([]);}else setTimeout(()=>setOpen([]),650)}};const reset=()=>{setCards([...symbols,...symbols].sort(()=>Math.random()-.5));setOpen([]);setSolved([]);setMoves(0)};const integers=(value:unknown,max:number)=>Array.isArray(value)&&value.length<=max&&value.every(item=>typeof item==="number"&&Number.isInteger(item)&&item>=0&&item<12)?value as number[]:null;return <GameFrame title="Memory Match" score={solved.length*100} paused={paused} setPaused={setPaused} onReset={reset} footer={<span>{moves} moves · find every matching pair</span>}><GameSessionBridge gameSlug="memory-match" state={{ cards, open, solved, moves, paused }} restore={(state)=>{if(Array.isArray(state.cards)&&state.cards.length===12&&state.cards.every(item=>symbols.includes(String(item))))setCards(state.cards as string[]);const nextOpen=integers(state.open,2),nextSolved=integers(state.solved,12);if(nextOpen)setOpen(nextOpen);if(nextSolved)setSolved(nextSolved);if(typeof state.moves==="number"&&state.moves>=0)setMoves(state.moves);setPaused(Boolean(state.paused));}}/><div className="memory-grid">{cards.map((symbol,index)=><button onClick={()=>choose(index)} className={open.includes(index)||solved.includes(index)?"flipped":""} key={`${symbol}-${index}`}>{open.includes(index)||solved.includes(index)?symbol:"?"}</button>)}</div></GameFrame>}

const minePositions = new Set([3,12,18,27,31,43,53,60,62]);
function MinesweeperGame(){const [open,setOpen]=useState<number[]>([]);const [flagged,setFlagged]=useState<number[]>([]);const [lost,setLost]=useState(false);const neighbours=(i:number)=>[-9,-8,-7,-1,1,7,8,9].filter(d=>{const next=i+d;return next>=0&&next<64&&Math.abs((next%8)-(i%8))<=1});const reset=()=>{setOpen([]);setFlagged([]);setLost(false)};const click=(index:number)=>{if(lost||flagged.includes(index))return;if(minePositions.has(index)){setLost(true);setOpen(Array.from({length:64},(_,cell)=>cell).filter(i=>minePositions.has(i)));}else setOpen(old=>[...old,index]);};const cells=(value:unknown)=>Array.isArray(value)&&value.length<=64&&value.every(item=>typeof item==="number"&&Number.isInteger(item)&&item>=0&&item<64)?value as number[]:null;return <GameFrame title="Minesweeper" score={open.filter(i=>!minePositions.has(i)).length*10} onReset={reset} footer={<span>{lost?"Mine hit — reset to try again.":"Tap a cell; right click / long press to flag."}</span>}><GameSessionBridge gameSlug="minesweeper" state={{ open, flagged, lost }} restore={(state)=>{const nextOpen=cells(state.open),nextFlagged=cells(state.flagged);if(nextOpen)setOpen(nextOpen);if(nextFlagged)setFlagged(nextFlagged);setLost(Boolean(state.lost));}}/><div className="mines-grid">{Array.from({length:64}).map((_,index)=>{const shown=open.includes(index), mine=minePositions.has(index), count=neighbours(index).filter(i=>minePositions.has(i)).length;return <button onClick={()=>click(index)} onContextMenu={(e)=>{e.preventDefault();setFlagged(o=>o.includes(index)?o.filter(v=>v!==index):[...o,index])}} className={shown?mine?"mine":"open":""} key={index}>{shown?(mine?"✕":count||""):flagged.includes(index)?"⚑":""}</button>})}</div></GameFrame>}

const sudokuSolution=[1,2,3,4,3,4,1,2,2,1,4,3,4,3,2,1]; const sudokuGiven=new Set([0,1,4,7,8,10,13,15]);
function SudokuGame(){const [values,setValues]=useState<(number|null)[]>(sudokuSolution.map((v,i)=>sudokuGiven.has(i)?v:null));const [selected,setSelected]=useState<number|null>(null);const reset=()=>setValues(sudokuSolution.map((v,i)=>sudokuGiven.has(i)?v:null));const complete=values.every((v,i)=>v===sudokuSolution[i]);return <GameFrame title="Sudoku" score={complete?200:0} onReset={reset} footer={<div className="sudoku-numbers">{[1,2,3,4].map(n=><button key={n} disabled={selected===null} onClick={()=>selected!==null&&!sudokuGiven.has(selected)&&setValues(old=>old.map((v,i)=>i===selected?n:v))}>{n}</button>)}<span>{complete?"Solved!":"Complete each row and column."}</span></div>}><GameSessionBridge gameSlug="sudoku" state={{ values, selected }} restore={(state)=>{if(Array.isArray(state.values)&&state.values.length===16&&state.values.every(value=>value===null||(typeof value==="number"&&value>=1&&value<=4)))setValues(state.values as (number|null)[]);if(typeof state.selected==="number"&&Number.isInteger(state.selected)&&state.selected>=0&&state.selected<16)setSelected(state.selected);}}/><div className="sudoku-grid">{values.map((value,index)=><button key={index} onClick={()=>!sudokuGiven.has(index)&&setSelected(index)} className={`${sudokuGiven.has(index)?"given":""} ${selected===index?"selected":""}`}>{value??""}</button>)}</div></GameFrame>}

function TicTacToeGame(){const [grid,setGrid]=useState<string[]>(Array(9).fill(""));const [turn,setTurn]=useState("X");const winner=useMemo(()=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].map(line=>grid[line[0]]&&grid[line[0]]===grid[line[1]]&&grid[line[1]]===grid[line[2]]?grid[line[0]]:"").find(Boolean)||"",[grid]);const play=(i:number)=>{if(turn!=="X"||grid[i]||winner)return;setGrid(old=>old.map((v,n)=>n===i?"X":v));setTurn("O")};useEffect(()=>{if(turn!=="O"||winner)return;const timer=window.setTimeout(()=>{setGrid(old=>{const choice=old[4]?old.findIndex(value=>!value):4;return old.map((value,index)=>index===choice?"O":value)});setTurn("X")},420);return()=>window.clearTimeout(timer)},[turn,winner]);const reset=()=>{setGrid(Array(9).fill(""));setTurn("X")};return <GameFrame title="Tic Tac Toe" score={winner==="X"?100:winner==="O"?50:0} onReset={reset} footer={<span>{winner?`${winner} wins!`:(turn==="O"?"AI is choosing…":"Your turn — you are X.")}</span>}><GameSessionBridge gameSlug="tic-tac-toe" state={{ grid, turn }} restore={(state)=>{if(Array.isArray(state.grid)&&state.grid.length===9&&state.grid.every(value=>value===""||value==="X"||value==="O"))setGrid(state.grid as string[]);setTurn(state.turn==="O"?"O":"X");}}/><div className="tictactoe-grid">{grid.map((value,index)=><button key={index} disabled={turn!=="X"||Boolean(winner)} onClick={()=>play(index)}>{value}</button>)}</div></GameFrame>}

export function PlayableGame({ slug }: { slug: string }) { const games:Record<string,React.ReactNode>={wordle:<WordleGame/>,"2048":<Game2048/>,snake:<SnakeGame/>,tetris:<TetrisGame/>,"memory-match":<MemoryGame/>,minesweeper:<MinesweeperGame/>,sudoku:<SudokuGame/>,"tic-tac-toe":<TicTacToeGame/>};return <>{games[slug]??null}</>; }
