export type Locale = "en" | "bn";
export const translations = {
  en: {
    "nav.tools": "Tools", "nav.games": "Games", "nav.ai": "AI", "nav.links": "Links",
    "search.placeholder": "Search tools & games…", "search.aria": "Search every tool and game",
    "theme.toggle": "Toggle color theme", "theme.label": "Theme", "language.switch": "বাংলা",
    "footer.privacy": "No data goes anywhere—everything runs in your browser. No sign-up required.",
    "footer.open": "Open source · MIT License · Built for Bangladesh", "footer.browse": "Browse", "footer.settings": "Settings",
    "footer.allTools": "All tools", "footer.games": "Original games", "footer.links": "Useful links", "footer.privacyLink": "Privacy", "footer.howTo": "How it works",
    "data.title": "My Data", "data.intro": "Your preferences, notes, AI keys, chat history and game saves stay only in this browser. We collect nothing.",
    "data.download.title": "Download my data", "data.download.description": "Save all local data in one JSON backup.", "data.download.action": "Download",
    "data.import.title": "Import data", "data.import.description": "Safely merge a previous backup into this browser.", "data.import.action": "Choose file",
    "data.clear.title": "Clear my data", "data.clear.description": "All local settings, saves and history will be permanently removed.", "data.clear.action": "Clear", "data.clear.again": "Press again", "data.clear.final": "Final confirm",
    "data.invalid": "This is not a valid Tools & Games BD backup.", "data.imported": "{count} local data items restored. Refresh the page.", "data.importFailed": "Storage is full or unavailable—import could not finish.", "data.cleared": "All local data was removed. Refresh the page.", "data.clearFailed": "Could not clear data—check browser storage access.",
    "data.warning": "If storage is full, new saves may not persist; the site will not crash.", "data.restore.title": "Restore this backup?", "data.restore.description": "Current data will not be erased. If a key already exists, the backup version will be used.", "data.cancel": "Cancel", "data.restore.action": "Merge & restore",
    "common.copy": "Copy", "common.download": "Download", "common.example": "Load example", "common.clear": "Clear", "common.reset": "Reset", "common.close": "Close", "common.back": "Back", "common.play": "Play now", "common.resume": "Resume", "common.save": "Save", "common.error": "Something went wrong. Please try again.",
    "memory.restore": "Restore your previous input", "memory.private": "Sensitive input is never remembered.", "memory.full": "Browser storage is full. This input will not be remembered.",
    "game.storageFull": "Browser storage is full. Your current game continues, but new progress may not be saved.", "game.best": "Best", "game.score": "Score", "game.level": "Level", "game.resources": "Resources", "game.pause": "Pause", "game.resume": "Resume", "game.instructions": "How to play", "game.fullscreen": "Fullscreen", "game.exit": "Back to games",
    "tool.input": "Input", "tool.output": "Output", "tool.run": "Run", "tool.browserOnly": "Browser-only", "tool.privacy": "No input ever leaves this browser.",
    "home.eyebrow": "THE PRIVATE BROWSER WORKBENCH", "home.titleA": "Useful tools.", "home.titleB": "Original games.", "home.titleC": "Zero sign-up.", "home.copy": "Work, create and take a proper play break—without giving up your data. Every core tool runs locally in your browser.", "home.tools": "Explore tools", "home.games": "Play games", "home.statTools": "200+ tools", "home.statGames": "32 games", "home.statFree": "100% free", "home.statPrivacy": "No sign-up", "home.featured": "Featured workbench", "home.featuredCopy": "Start with a useful, everyday tool.", "home.categories": "Choose an instrument tray", "home.categoriesCopy": "Tools grouped by how you think—not by what a server can collect.", "home.gameKicker": "PLAY LOCALLY", "home.gamesTitle": "A better kind of break.", "home.gamesCopy": "Original browser games, designed for keyboard and touch, with every high score saved only on your device.", "home.aiKicker": "BRING YOUR OWN KEY", "home.aiTitle": "AI when you choose it.", "home.aiCopy": "Connect your own provider key locally, or use free browser voice tools—no account with us required.", "home.viewAi": "Visit AI tools", "home.viewAll": "View all",
    "tools.eyebrow": "THE TOOL DIRECTORY", "tools.title": "Find your next shortcut.", "tools.copy": "Every tool is local-first, fast and designed to be useful before it is impressive.", "tools.all": "All categories", "tools.resultCount": "{count} tools", "tools.empty": "No tool found for that search. Try a simpler word.",
    "games.eyebrow": "ORIGINAL BROWSER GAMES", "games.title": "Take a skillful break.", "games.copy": "No ads, no online lobby and no account. Just original games that respond to keyboard and touch.", "games.all": "All genres", "games.count": "{count} games", "games.empty": "No game found in this genre.",
    "links.eyebrow": "USEFUL LINKS DIRECTORY", "links.title": "Trusted places to keep close.", "links.copy": "A hand-picked, searchable directory for learning, making, work and everyday life in Bangladesh.", "links.search": "Search useful sites…", "links.visit": "Visit site", "links.all": "All directories", "links.empty": "No useful link found.",
    "ai.eyebrow": "BRING YOUR OWN API KEY", "ai.title": "Your key. Your browser. Your call.", "ai.copy": "Optional AI features run directly between your browser and the provider you select. We do not proxy, collect or inspect your keys.", "ai.stepsTitle": "Set up in six clear steps", "ai.step1": "Go to the provider link", "ai.step2": "Sign in to your own account", "ai.step3": "Create an API key", "ai.step4": "Copy it", "ai.step5": "Paste it into the relevant AI tool", "ai.step6": "That’s it—clear it anytime from My Data.", "ai.security": "Security note: Your key stays in this browser’s local storage. We never receive it.", "ai.providers": "Recommended providers", "ai.free": "Free, no-key voice tools", "ai.speech": "Browser Speech to Text", "ai.tts": "Browser Text to Speech", "ai.recorder": "Voice Recorder",
    "static.about.title": "Made for useful internet time.", "static.about.copy": "Tools & Games BD is a client-side collection of everyday utilities, original browser games and useful links. It is built around the simple belief that a good tool should respect its user.", "static.how.title": "How it works", "static.how.copy": "Open a tool, add your input and get a result instantly. Copy or download it when you are done. Your ordinary tool input, game saves and preferences can be restored from this device only.", "static.privacy.title": "Private by construction.", "static.privacy.copy": "We do not run an account system, tracking pixels, analytics or a server that receives your tool inputs. Core processing happens in your browser. Optional AI calls go directly from your browser to the provider whose key you choose.", "static.notFound.title": "This workbench drawer is empty.", "static.notFound.copy": "The page you requested is not here. Search a tool or return to the home workbench.",
    "appearance.title": "Custom Theme", "appearance.copy": "Choose a familiar developer palette or build a private theme token-by-token. Every change stays in this browser.", "appearance.mode": "Appearance", "appearance.use": "Use this theme", "appearance.edit": "Edit theme", "appearance.delete": "Delete theme", "appearance.create": "Create your own theme", "appearance.reset": "Reset", "appearance.name": "Theme name", "appearance.namePlaceholder": "e.g. My Cobalt Desk", "appearance.save": "Save theme", "appearance.export": "Export theme", "appearance.import": "Import theme", "appearance.paste": "Paste clipboard", "appearance.importPlaceholder": "Paste a six-token theme JSON object here…", "appearance.copied": "Theme JSON copied to the clipboard.", "appearance.imported": "Theme tokens loaded into the editor.", "appearance.invalid": "That is not a valid six-token theme JSON object.", "appearance.nameRequired": "Give your custom theme a name before saving.", "appearance.saved": "Your custom theme was saved locally.", "appearance.defaulted": "Built-in Light theme restored and custom themes cleared.", "appearance.resetDefault": "Reset to default", "settings.title": "Settings", "settings.copy": "Set your language, theme and local data controls exactly as you prefer.",
  },
  bn: {
    "nav.tools": "টুলস", "nav.games": "গেমস", "nav.ai": "AI", "nav.links": "লিংকস",
    "search.placeholder": "টুল বা গেম খুঁজুন…", "search.aria": "সব টুল ও গেম সার্চ", "theme.toggle": "থিম বদলান", "theme.label": "থিম", "language.switch": "EN",
    "footer.privacy": "কোনো data কোথাও পাঠানো হয় না — সবকিছু আপনার browser-এই কাজ করে। কোনো sign-up লাগে না।", "footer.open": "ওপেন সোর্স · MIT License · বাংলাদেশের জন্য তৈরি", "footer.browse": "ব্রাউজ করুন", "footer.settings": "সেটিংস",
    "footer.allTools": "সব টুল", "footer.games": "অরিজিনাল গেম", "footer.links": "দরকারি লিংক", "footer.privacyLink": "গোপনীয়তা", "footer.howTo": "কীভাবে ব্যবহার করবেন",
    "data.title": "আমার ডেটা", "data.intro": "আপনার পছন্দ, নোট, AI key, chat history এবং game save শুধুই এই browser-এ থাকে। আমরা কিছুই সংগ্রহ করি না।",
    "data.download.title": "ডেটা ডাউনলোড", "data.download.description": "সব local data এক JSON backup-এ রাখুন।", "data.download.action": "Download",
    "data.import.title": "ডেটা ইমপোর্ট", "data.import.description": "পুরনো backup নিরাপদভাবে merge করে ফিরিয়ে আনুন।", "data.import.action": "ফাইল বাছুন",
    "data.clear.title": "ডেটা মুছুন", "data.clear.description": "সব local setting, save ও history স্থায়ীভাবে মুছে যাবে।", "data.clear.action": "Clear", "data.clear.again": "আবার চাপুন", "data.clear.final": "শেষ নিশ্চিতকরণ",
    "data.invalid": "ফাইলটি Tools & Games BD-এর বৈধ backup নয়।", "data.imported": "{count}টি local data item restore হয়েছে। পেজটি refresh করুন।", "data.importFailed": "Storage পূর্ণ বা browser storage বন্ধ আছে—import সম্পন্ন হয়নি।", "data.cleared": "সব local data মুছে গেছে। পেজটি refresh করুন।", "data.clearFailed": "Data মুছতে পারেনি—browser storage access পরীক্ষা করুন।",
    "data.warning": "Storage পূর্ণ হলে নতুন data save নাও হতে পারে; সাইট ক্র্যাশ করবে না।", "data.restore.title": "Backup restore করবেন?", "data.restore.description": "বর্তমান data মুছবে না। একই key থাকলে backup-এর সংস্করণটি ব্যবহার হবে।", "data.cancel": "বাতিল", "data.restore.action": "Merge ও restore",
    "common.copy": "কপি করুন", "common.download": "ডাউনলোড", "common.example": "উদাহরণ দেখুন", "common.clear": "মুছুন", "common.reset": "রিসেট", "common.close": "বন্ধ", "common.back": "ফিরে যান", "common.play": "এখন খেলুন", "common.resume": "আবার শুরু করুন", "common.save": "সেভ", "common.error": "সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    "memory.restore": "আগের input রেস্টোর করুন", "memory.private": "সংবেদনশীল input কখনো মনে রাখা হয় না।", "memory.full": "Browser storage পূর্ণ। এই input মনে রাখা যাবে না।",
    "game.storageFull": "Browser storage পূর্ণ। গেম চলবে, কিন্তু নতুন progress save নাও হতে পারে।", "game.best": "সেরা", "game.score": "স্কোর", "game.level": "লেভেল", "game.resources": "রিসোর্স", "game.pause": "বিরতি", "game.resume": "আবার শুরু", "game.instructions": "কীভাবে খেলবেন", "game.fullscreen": "ফুলস্ক্রিন", "game.exit": "গেমে ফিরুন",
    "tool.input": "ইনপুট", "tool.output": "আউটপুট", "tool.run": "চালান", "tool.browserOnly": "শুধু ব্রাউজারে", "tool.privacy": "কোনো input এই browser-এর বাইরে যায় না।",
    "home.eyebrow": "ব্যক্তিগত ব্রাউজার ওয়ার্কবেঞ্চ", "home.titleA": "দরকারি টুলস।", "home.titleB": "অরিজিনাল গেমস।", "home.titleC": "কোনো sign-up নেই।", "home.copy": "কাজ করুন, তৈরি করুন এবং ঠিকঠাক বিরতি নিন—নিজের data ছেড়ে না দিয়ে। প্রতিটি মূল টুল আপনার browser-এই কাজ করে।", "home.tools": "টুলস দেখুন", "home.games": "গেম খেলুন", "home.statTools": "২০০+ টুল", "home.statGames": "৩২ গেম", "home.statFree": "১০০% ফ্রি", "home.statPrivacy": "কোনো sign-up নেই", "home.featured": "ফিচারড ওয়ার্কবেঞ্চ", "home.featuredCopy": "প্রতিদিনের দরকারি একটি টুল দিয়ে শুরু করুন।", "home.categories": "নিজের instrument tray বাছুন", "home.categoriesCopy": "যেভাবে ভাবেন, সেভাবে টুল সাজানো—কোনো server কী collect করতে পারে, তা দিয়ে নয়।", "home.gameKicker": "লোকালেই খেলুন", "home.gamesTitle": "বিরতিটা আরও ভালো হোক।", "home.gamesCopy": "Keyboard আর touch-এর জন্য তৈরি অরিজিনাল browser game; সব high score শুধু আপনার device-এ সেভ হয়।", "home.aiKicker": "নিজের key ব্যবহার করুন", "home.aiTitle": "AI, যখন আপনি চান।", "home.aiCopy": "নিজের provider key লোকালেই যুক্ত করুন, অথবা ফ্রি browser voice tool ব্যবহার করুন—আমাদের সাইটে কোনো account লাগবে না।", "home.viewAi": "AI টুল দেখুন", "home.viewAll": "সব দেখুন",
    "tools.eyebrow": "টুল ডিরেক্টরি", "tools.title": "পরের shortcut খুঁজে নিন।", "tools.copy": "প্রতিটি টুল local-first, দ্রুত এবং দেখানোর আগে কাজে লাগার জন্য তৈরি।", "tools.all": "সব ক্যাটাগরি", "tools.resultCount": "{count}টি টুল", "tools.empty": "এই খোঁজে কোনো টুল পাওয়া যায়নি। সহজ শব্দ দিয়ে চেষ্টা করুন।",
    "games.eyebrow": "অরিজিনাল ব্রাউজার গেম", "games.title": "দক্ষতার সঙ্গে বিরতি নিন।", "games.copy": "কোনো ad নেই, online lobby নেই, account নেই। শুধু keyboard ও touch-এ সাড়া দেওয়া অরিজিনাল গেম।", "games.all": "সব genre", "games.count": "{count}টি গেম", "games.empty": "এই genre-এ কোনো গেম পাওয়া যায়নি।",
    "links.eyebrow": "দরকারি লিংক ডিরেক্টরি", "links.title": "হাতের কাছে রাখার মতো নির্ভরযোগ্য জায়গা।", "links.copy": "বাংলাদেশে শেখা, তৈরি, কাজ এবং প্রতিদিনের প্রয়োজনের জন্য বাছাই করা searchable directory।", "links.search": "দরকারি সাইট খুঁজুন…", "links.visit": "সাইটে যান", "links.all": "সব ডিরেক্টরি", "links.empty": "কোনো দরকারি লিংক পাওয়া যায়নি।",
    "ai.eyebrow": "নিজের API KEY ব্যবহার করুন", "ai.title": "আপনার key। আপনার browser। আপনার সিদ্ধান্ত।", "ai.copy": "ঐচ্ছিক AI feature আপনার browser ও বেছে নেওয়া provider-এর মধ্যে সরাসরি কাজ করে। আমরা আপনার key proxy, collect বা inspect করি না।", "ai.stepsTitle": "ছয়টি সহজ ধাপে সেটআপ", "ai.step1": "Provider-এর লিংকে যান", "ai.step2": "নিজের account-এ sign in করুন", "ai.step3": "একটি API key তৈরি করুন", "ai.step4": "Key copy করুন", "ai.step5": "প্রাসঙ্গিক AI tool-এ paste করুন", "ai.step6": "ব্যস—চাইলে My Data থেকে যেকোনো সময় clear করুন।", "ai.security": "নিরাপত্তা নোট: আপনার key এই browser-এর local storage-এই থাকে। আমরা কখনো পাই না।", "ai.providers": "সুপারিশকৃত provider", "ai.free": "ফ্রি, key ছাড়া voice tool", "ai.speech": "Browser Speech to Text", "ai.tts": "Browser Text to Speech", "ai.recorder": "Voice Recorder",
    "static.about.title": "ইন্টারনেটে কাজে লাগা সময়ের জন্য তৈরি।", "static.about.copy": "Tools & Games BD হলো দৈনন্দিন utility, অরিজিনাল browser game ও দরকারি লিংকের client-side সংগ্রহ। সহজ বিশ্বাসটিই এর ভিত্তি: ভালো tool তার user-কে সম্মান করে।", "static.how.title": "কীভাবে কাজ করে", "static.how.copy": "একটি tool খুলুন, input দিন এবং সঙ্গে সঙ্গে result পান। শেষ হলে copy বা download করুন। সাধারণ tool input, game save এবং পছন্দগুলো কেবল এই device থেকেই restore করা যায়।", "static.privacy.title": "নকশাতেই ব্যক্তিগত।", "static.privacy.copy": "আমরা account system, tracking pixel, analytics বা এমন কোনো server চালাই না যা আপনার tool input পায়। মূল processing আপনার browser-এ হয়। ঐচ্ছিক AI call আপনার browser থেকে আপনার বেছে নেওয়া provider-এর কাছে সরাসরি যায়।", "static.notFound.title": "এই ওয়ার্কবেঞ্চের ড্রয়ারটি খালি।", "static.notFound.copy": "আপনি যে পেজটি চেয়েছেন, তা এখানে নেই। একটি tool search করুন অথবা home workbench-এ ফিরে যান।",
    "appearance.title": "কাস্টম থিম", "appearance.copy": "পরিচিত developer palette বাছুন, অথবা token ধরে নিজের ব্যক্তিগত theme তৈরি করুন। প্রতিটি পরিবর্তন এই browser-এই থাকে।", "appearance.mode": "অ্যাপিয়ারেন্স", "appearance.use": "এই থিম ব্যবহার করুন", "appearance.edit": "থিম এডিট", "appearance.delete": "থিম মুছুন", "appearance.create": "নিজের থিম তৈরি করুন", "appearance.reset": "রিসেট", "appearance.name": "থিমের নাম", "appearance.namePlaceholder": "যেমন: আমার কোবাল্ট ডেস্ক", "appearance.save": "থিম সেভ করুন", "appearance.export": "থিম এক্সপোর্ট", "appearance.import": "থিম ইমপোর্ট", "appearance.paste": "ক্লিপবোর্ড পেস্ট", "appearance.importPlaceholder": "এখানে ছয়-token theme JSON object পেস্ট করুন…", "appearance.copied": "Theme JSON ক্লিপবোর্ডে কপি হয়েছে।", "appearance.imported": "Theme token editor-এ লোড হয়েছে।", "appearance.invalid": "এটি বৈধ ছয়-token theme JSON object নয়।", "appearance.nameRequired": "সেভ করার আগে custom theme-এর একটি নাম দিন।", "appearance.saved": "আপনার custom theme লোকালি save হয়েছে।", "appearance.defaulted": "Built-in Light theme ফিরেছে এবং custom theme মুছে গেছে।", "appearance.resetDefault": "ডিফল্টে ফিরুন", "settings.title": "সেটিংস", "settings.copy": "ভাষা, থিম ও local data control নিজের পছন্দমতো সাজান।",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function interpolate(template: string, values?: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_match, key) => String(values?.[key] ?? `{${key}}`));
}
