export type Locale = "en" | "bn";

/**
 * English is the source of truth: `TranslationKey` is derived from it, and `bn` is
 * typed as a complete record of those keys. A missing or misspelled Bangla key is a
 * compile error rather than a silent fallback to English at runtime.
 */
const en = {
  "nav.tools": "Tools", "nav.games": "Games", "nav.ai": "AI", "nav.links": "Links",
  "search.placeholder": "Search tools & games…", "search.aria": "Search every tool and game",
  "theme.toggle": "Toggle color theme", "theme.label": "Theme", "language.switch": "বাংলা",
  "footer.privacy": "No data goes anywhere—everything runs in your browser. No sign-up required.",
  "footer.open": "Open source · MIT License · Built for Bangladesh", "footer.browse": "Browse", "footer.settings": "Settings",
  "footer.allTools": "All tools", "footer.games": "Original games", "footer.links": "Useful links", "footer.privacyLink": "Privacy", "footer.howTo": "How it works", "footer.copyright": "© {year} Tools & Games BD",
  "data.title": "My Data", "data.intro": "Your preferences, notes, game saves and themes stay only in this browser. We collect nothing. Fonts load from Google Fonts, which sees standard request data.",
  "data.download.title": "Download my data", "data.download.description": "Save all local data in one JSON backup.", "data.download.action": "Download",
  "data.import.title": "Import data", "data.import.description": "Restore a previous backup into this browser.", "data.import.action": "Choose file",
  "data.clear.title": "Clear my data", "data.clear.description": "All local settings, saves and history will be permanently removed.", "data.clear.action": "Clear", "data.clear.again": "Press again", "data.clear.final": "Final confirm",
  "data.clear.confirmTitle": "Clear all local data?", "data.clear.confirmCopy": "This removes every setting, saved input, game save and theme this site created in this browser. Data saved by other sites is never touched. This cannot be undone.", "data.clear.confirmAction": "Yes, clear my data",
  "data.invalid": "This is not a valid Tools & Games BD backup.", "data.imported": "{count} local data items restored.", "data.importFailed": "Storage is full or unavailable—import could not finish.", "data.cleared": "{count} local data items removed.", "data.clearFailed": "Could not clear data—check browser storage access.",
  "data.warning": "If storage is full, new saves may not persist; the site will not crash.", "data.restore.title": "Restore this backup?", "data.restore.description": "Choose how the backup should be applied. Nothing is written until you confirm.", "data.cancel": "Cancel", "data.restore.action": "Restore",
  "data.mode.label": "How should the backup be applied?", "data.mode.merge": "Merge", "data.mode.merge.description": "Keeps everything already in this browser. Where the backup has the same item, the backup version wins.", "data.mode.replace": "Replace", "data.mode.replace.description": "Removes this site's current local data first, then restores only what the backup contains.",
  "data.restore.mergeAction": "Merge & restore", "data.restore.replaceAction": "Replace & restore",
  "data.report.merge": "{imported} items restored, {unchanged} left unchanged.", "data.report.replace": "{imported} items restored, {removed} removed.",
  "data.selected": "Selected file: {name}", "data.empty": "There is nothing saved in this browser yet.", "data.downloaded": "Backup with {count} items saved to your device.",
  "data.error.read": "That file could not be read. Choose the downloaded .json backup.", "data.error.invalid": "That file is not valid JSON.", "data.error.version": "That backup was made by a newer version of this site and cannot be read safely.", "data.error.source": "That backup was not created by Tools & Games BD.", "data.error.shape": "That backup is missing the expected fields.", "data.error.namespace": "That backup contains items that do not belong to this site. Nothing was changed.", "data.error.size": "That backup is too large to restore safely.", "data.error.quota": "Browser storage is full. Nothing was changed.", "data.error.unavailable": "Browser storage is unavailable—private browsing may be blocking it.",
  "common.copy": "Copy", "common.download": "Download", "common.example": "Load example", "common.clear": "Clear", "common.reset": "Reset", "common.close": "Close", "common.back": "Back", "common.resume": "Resume", "common.save": "Save", "common.loading": "Loading…", "common.error": "Something went wrong. Please try again.",
  "memory.restore": "Restore your previous input", "memory.private": "Sensitive input is never remembered.", "memory.full": "Browser storage is full. This input will not be remembered.", "memory.forget": "Forget this input", "memory.forgotten": "Saved input for this tool was removed.", "memory.tooLarge": "This input is too long to remember. It still works normally.",
  "error.title": "This page hit an unexpected error.", "error.copy": "Nothing was sent anywhere and your saved data is untouched. Try again, or go back to the home workbench.", "error.details": "Technical details", "error.retry": "Try again", "error.home": "Go home",
  "notFound.code": "404 — NOT FOUND", "notFound.home": "Home workbench",
  "game.storageFull": "Browser storage is full. Your current game continues, but new progress may not be saved.", "game.best": "Best", "game.score": "Score", "game.level": "Level", "game.resources": "Resources", "game.food": "Food", "game.lines": "Lines", "game.next": "Next", "game.tile": "Best tile", "game.moves": "Moves", "game.gaps": "Gaps", "game.lives": "Lives", "game.pause": "Pause", "game.resume": "Resume", "game.fullscreen": "Fullscreen", "game.exit": "Back to games",
  "control.up": "Up", "control.down": "Down", "control.left": "Left", "control.right": "Right",
  "control.primary": "Action", "control.secondary": "Second action", "control.rotateCw": "Rotate right", "control.rotateCcw": "Rotate left",
  "control.drop": "Drop", "control.erase": "Erase", "control.letters": "Letters", "control.digits": "Numbers",
  "key.space": "Space", "key.enter": "Enter", "key.escape": "Esc", "key.shift": "Shift", "key.backspace": "Backspace", "key.delete": "Delete",
  "game.start": "Start", "game.restart": "Restart", "game.playAgain": "Play again",
  "game.paused": "Paused", "game.pausedCopy": "The game is on hold. Nothing moves until you resume.", "game.pausedHidden": "Paused because this tab went to the background.",
  "game.over": "Game over", "game.overCopy": "Your score is saved. Play again to try for a higher one.", "game.overWithScore": "Game over. Score {score}, best {best}.",
  "game.readyTitle": "Ready", "game.readyCopy": "Press Space, or tap Start, to begin.",
  "game.exitFullscreen": "Exit fullscreen", "game.controls.title": "Controls", "game.touchControls": "On-screen controls",
  "game.touchHint": "On a touchscreen, use the on-screen buttons above. Both sets of controls do exactly the same thing.",
  "game.comingSoon.badge": "Coming soon", "game.comingSoon.title": "This game is not finished yet.",
  "game.comingSoon.copy": "Rather than publish a board that half works, this one stays listed until it plays properly with both a keyboard and touch. Every game marked playable is finished.",
  "games.playableBadge": "Playable",
  "game.forget": "Forget this save", "game.missing.title": "That game is not in the cabinet.", "game.missing.copy": "No game matches this address. Browse the full list and pick another one.",
  "tool.input": "Input", "tool.output": "Output", "tool.run": "Run", "tool.browserOnly": "Browser-only", "tool.privacy": "No input ever leaves this browser.",
  "tool.inputLabel": "{name} input", "tool.mode.label": "Tool mode", "tool.mode.default": "Default", "tool.mode.decode": "Decode", "tool.mode.words": "Words", "tool.mode.lines": "Lines", "tool.mode.desc": "Z to A", "tool.mode.bulk": "Bulk ×10", "tool.mode.yaml": "YAML", "tool.mode.xml": "XML", "tool.mode.unescape": "Unescape",
  "tool.copied": "Result copied to the clipboard.", "tool.copyFailed": "Could not reach the clipboard. Select the result and copy it manually.", "tool.downloaded": "Result saved to your device.",
  "tool.missing.title": "That tool is not in this drawer.", "tool.missing.copy": "No tool matches this address. Search the directory and try a simpler word.",
  "tool.unavailable.badge": "Not built yet", "tool.unavailable.title": "This tool is listed but not built yet.", "tool.unavailable.copy": "It is on the roadmap. Nothing is sent anywhere and no half-working result is shown, so you are not misled by output that looks real.",
  "tool.result.stats": "Live statistics", "tool.result.preview": "Sanitized preview HTML", "tool.result.needsInput": "Add an input to see an immediate, browser-only result.", "tool.result.notesHint": "Your notes stay in this browser on this device.", "tool.result.signaturePresent": "Present — not verified locally", "tool.result.signatureMissing": "Missing",
  "tool.bmi.underweight": "Underweight", "tool.bmi.healthy": "Healthy range", "tool.bmi.overweight": "Overweight", "tool.bmi.obese": "Obesity range",
  "tool.error.generic": "Check the input and try again.", "tool.error.octal": "Enter a valid octal mode, for example 755.", "tool.error.hex": "Enter a 6-digit HEX colour, for example #3264FF.", "tool.error.jwt": "Enter a token in header.payload.signature form.", "tool.error.number": "Enter one or two numbers separated by a space or comma.",
  "tool.error.math.badChar": "Only numbers, operators and known function names are allowed.", "tool.error.math.badSyntax": "The expression is incomplete or has an unmatched bracket.", "tool.error.math.unknownName": "Unknown function or constant name.", "tool.error.math.badArgs": "That function was given the wrong number of arguments.", "tool.error.math.notFinite": "The result is not a finite number.", "tool.error.math.tooLong": "The expression is too long.",
  "tool.error.fileTooLarge": "That file is too large to hash in the browser (max 50 MB).", "tool.hash.note": "Hashes are computed locally with Web Crypto. SHA-1 is a checksum only — never use hashes to store passwords.", "tool.file.choose": "Choose file", "tool.file.selected": "Selected file: {name} ({size})", "tool.file.hashNote": "Files are read only on this device to compute hashes. Nothing is uploaded.", "tool.file.noFile": "Choose a file to compute its SHA hashes locally.", "tool.file.cancel": "Remove file",
  "home.eyebrow": "THE PRIVATE BROWSER WORKBENCH", "home.metaTitle": "Useful tools, original games, zero sign-up", "home.titleA": "Useful tools.", "home.titleB": "Original games.", "home.titleC": "Zero sign-up.", "home.copy": "Work, create and take a proper play break—without giving up your data. Every core tool runs locally in your browser.", "home.tools": "Explore tools", "home.games": "Play games", "home.statTools": "200+ tools", "home.statGames": "32 games", "home.statFree": "100% free", "home.statPrivacy": "No sign-up", "home.featured": "Featured workbench", "home.featuredCopy": "Start with a useful, everyday tool.", "home.categories": "Choose an instrument tray", "home.categoriesCopy": "Tools grouped by how you think—not by what a server can collect.", "home.gameKicker": "PLAY LOCALLY", "home.gamesTitle": "A better kind of break.", "home.gamesCopy": "Original browser games. Every one marked playable works with a keyboard and with touch, and high scores are saved only on your device.", "home.aiKicker": "BRING YOUR OWN KEY", "home.aiTitle": "AI when you choose it.", "home.aiCopy": "Connect your own provider key locally, or use free browser voice tools—no account with us required.", "home.viewAi": "Visit AI tools", "home.viewAll": "View all",
  "tools.eyebrow": "THE TOOL DIRECTORY", "tools.title": "Find your next shortcut.", "tools.copy": "Every tool is local-first, fast and designed to be useful before it is impressive.", "tools.all": "All categories", "tools.resultCount": "{count} tools", "tools.empty": "No tool found for that search. Try a simpler word.", "tools.filterLabel": "Filter tools by category", "tools.resultsHeading": "Matching tools",
  "games.eyebrow": "ORIGINAL BROWSER GAMES", "games.title": "Take a skillful break.", "games.copy": "No ads, no online lobby and no account. Every game marked playable works with a keyboard and with touch.", "games.all": "All genres", "games.count": "{count} games", "games.empty": "No game found in this genre.", "games.filterLabel": "Filter games by genre",
  "links.eyebrow": "USEFUL LINKS DIRECTORY", "links.title": "Trusted places to keep close.", "links.copy": "A hand-picked, searchable directory for learning, making, work and everyday life in Bangladesh.", "links.search": "Search useful sites…", "links.visit": "Visit site", "links.all": "All directories", "links.empty": "No useful link found.", "links.filterLabel": "Filter links by directory",
  "ai.eyebrow": "BRING YOUR OWN API KEY", "ai.title": "Your key. Your browser. Your call.", "ai.copy": "This page is a setup guide only — no AI call runs yet. When a future AI tool runs, it will go directly between your browser and the provider you select. We do not proxy, collect or inspect your keys. Fonts load from Google Fonts.", "ai.stepsTitle": "Set up in six clear steps", "ai.step1": "Go to the provider link", "ai.step2": "Sign in to your own account", "ai.step3": "Create an API key", "ai.step4": "Copy it", "ai.step5": "Paste it into the relevant AI tool", "ai.step6": "That’s it—clear it anytime from My Data.", "ai.security": "Security note: Your key stays in this browser’s local storage. We never receive it.", "ai.providers": "Recommended providers", "ai.free": "Free, no-key voice tools", "ai.speech": "Browser Speech to Text", "ai.tts": "Browser Text to Speech", "ai.recorder": "Voice Recorder",
  "static.about.title": "Made for useful internet time.", "static.about.copy": "Tools & Games BD is a client-side collection of everyday utilities, original browser games and useful links. It is built around the simple belief that a good tool should respect its user.", "static.how.title": "How it works", "static.how.copy": "Open a tool, add your input and get a result instantly. Copy or download it when you are done. Your ordinary tool input, game saves and preferences can be restored from this device only.", "static.privacy.title": "Private by construction.", "static.privacy.copy": "We do not run an account system, tracking pixels, analytics or a server that receives your tool inputs. Core processing happens in your browser. Fonts load from Google Fonts (standard request data). A future AI tool would call your chosen provider directly from your browser — nothing runs yet.", "static.notFound.title": "This workbench drawer is empty.", "static.notFound.copy": "The page you requested is not here. Search a tool or return to the home workbench.",
  "appearance.title": "Custom Theme", "appearance.copy": "Choose a familiar developer palette or build a private theme token-by-token. Every change stays in this browser.", "appearance.mode": "Appearance", "appearance.use": "Use this theme", "appearance.edit": "Edit theme", "appearance.delete": "Delete theme", "appearance.create": "Create your own theme", "appearance.reset": "Reset", "appearance.name": "Theme name", "appearance.namePlaceholder": "e.g. My Cobalt Desk", "appearance.save": "Save theme", "appearance.export": "Export theme", "appearance.import": "Import theme", "appearance.paste": "Paste clipboard", "appearance.importPlaceholder": "Paste a six-token theme JSON object here…", "appearance.copied": "Theme JSON copied to the clipboard.", "appearance.imported": "Theme tokens loaded into the editor.", "appearance.invalid": "That is not a valid six-token theme JSON object.", "appearance.nameRequired": "Give your custom theme a name before saving.", "appearance.saved": "Your custom theme was saved locally.", "appearance.defaulted": "Built-in Light theme restored and custom themes cleared.", "appearance.resetDefault": "Reset to default", "settings.title": "Settings", "settings.copy": "Set your language, theme and local data controls exactly as you prefer.",

  // Accessible names for controls whose visible label is an icon, plus the landmark
  // names screen readers announce. These were hardcoded English before Phase 2.
  "a11y.skip": "Skip to main content", "a11y.home": "Tools & Games BD — home", "a11y.mainNav": "Main navigation", "a11y.drawerNav": "Site menu",
  "a11y.openMenu": "Open menu", "a11y.closeMenu": "Close menu", "a11y.searchDrawer": "Search tools and games", "a11y.themeSwatches": "Palette preview", "a11y.currentTheme": "Current theme",
  "a11y.sortLabel": "Sort results", "a11y.viewLabel": "Result layout", "a11y.notifications": "Notifications",
  // The language button's visible text is the name of the *other* language, which
  // reads as a label rather than an action, so the accessible name states the action.
  "a11y.switchLanguage": "Switch site language to Bangla",

  // Theme panel. The six token names, the preview specimen copy and the two section
  // eyebrows were all hardcoded English in the component before Phase 2.
  "appearance.eyebrow": "APPEARANCE", "appearance.customEyebrow": "CUSTOM", "appearance.system": "Match my system",
  "appearance.tokenBackground": "Background", "appearance.tokenSurface": "Surface", "appearance.tokenText": "Text",
  "appearance.tokenPrimary": "Primary accent", "appearance.tokenSecondary": "Secondary accent", "appearance.tokenBorder": "Borders",
  "appearance.previewLabel": "LIVE PREVIEW", "appearance.previewHeading": "Useful work, clearly styled.",
  "appearance.previewCard": "Component card", "appearance.previewStrong": "Clean token hierarchy",
  "appearance.previewInput": "A styled input", "appearance.previewButton": "Primary action", "appearance.previewLink": "Secondary link",
  "appearance.importedName": "Imported theme", "appearance.previewRegion": "Live preview of the theme being edited",

  // Section eyebrows. The numbering is decorative sequence, the word is content, so
  // the whole label is one key rather than a number concatenated with a translation.
  "home.markWork": "01 / WORK", "home.markPlay": "02 / PLAY", "home.stepTools": "01 / TOOLS", "home.stepSelect": "02 / SELECT", "home.stepPlay": "03 / PLAY LOCALLY", "home.stepAi": "04 / BRING YOUR OWN KEY",
  "tools.instrumentTray": "INSTRUMENT TRAY", "settings.eyebrow": "CONTROL ROOM", "settings.dataEyebrow": "PRIVATE STORAGE", "static.eyebrow": "TOOLS & GAMES BD",

  // Live-region announcements. Screen readers get these; sighted users see the count
  // or the filter state change, so the wording states the outcome, not the action.
  "status.linksFiltered": "{count} links match the current filter.",
  "common.clearSearch": "Clear search", "links.newTab": "opens in a new tab",
} as const;

export type TranslationKey = keyof typeof en;

const bn: Record<TranslationKey, string> = {
  "nav.tools": "টুলস", "nav.games": "গেমস", "nav.ai": "AI", "nav.links": "লিংকস",
  "search.placeholder": "টুল বা গেম খুঁজুন…", "search.aria": "সব টুল ও গেম সার্চ",
  "theme.toggle": "থিম বদলান", "theme.label": "থিম", "language.switch": "EN",
  "footer.privacy": "কোনো data কোথাও পাঠানো হয় না — সবকিছু আপনার browser-এই কাজ করে। কোনো sign-up লাগে না।",
  "footer.open": "ওপেন সোর্স · MIT License · বাংলাদেশের জন্য তৈরি", "footer.browse": "ব্রাউজ করুন", "footer.settings": "সেটিংস",
  "footer.allTools": "সব টুল", "footer.games": "অরিজিনাল গেম", "footer.links": "দরকারি লিংক", "footer.privacyLink": "গোপনীয়তা", "footer.howTo": "কীভাবে ব্যবহার করবেন", "footer.copyright": "© {year} Tools & Games BD",
  "data.title": "আমার ডেটা", "data.intro": "আপনার পছন্দ, নোট, game save ও theme শুধুই এই browser-এ থাকে। আমরা কিছুই সংগ্রহ করি না। ফন্ট Google Fonts থেকে লোড হয়।",
  "data.download.title": "ডেটা ডাউনলোড", "data.download.description": "সব local data এক JSON backup-এ রাখুন।", "data.download.action": "ডাউনলোড",
  "data.import.title": "ডেটা ইমপোর্ট", "data.import.description": "পুরনো backup এই browser-এ ফিরিয়ে আনুন।", "data.import.action": "ফাইল বাছুন",
  "data.clear.title": "ডেটা মুছুন", "data.clear.description": "সব local setting, save ও history স্থায়ীভাবে মুছে যাবে।", "data.clear.action": "মুছুন", "data.clear.again": "আবার চাপুন", "data.clear.final": "শেষ নিশ্চিতকরণ",
  "data.clear.confirmTitle": "সব local data মুছে ফেলবেন?", "data.clear.confirmCopy": "এই সাইট এই browser-এ যে setting, saved input, game save ও theme তৈরি করেছে—সব মুছে যাবে। অন্য সাইটের data কখনোই ছোঁয়া হয় না। এটি ফেরানো যাবে না।", "data.clear.confirmAction": "হ্যাঁ, আমার data মুছুন",
  "data.invalid": "ফাইলটি Tools & Games BD-এর বৈধ backup নয়।", "data.imported": "{count}টি local data item restore হয়েছে।", "data.importFailed": "Storage পূর্ণ বা browser storage বন্ধ আছে—import সম্পন্ন হয়নি।", "data.cleared": "{count}টি local data item মুছে গেছে।", "data.clearFailed": "Data মুছতে পারেনি—browser storage access পরীক্ষা করুন।",
  "data.warning": "Storage পূর্ণ হলে নতুন data save নাও হতে পারে; সাইট ক্র্যাশ করবে না।", "data.restore.title": "Backup restore করবেন?", "data.restore.description": "Backup কীভাবে প্রয়োগ হবে তা বাছুন। আপনি নিশ্চিত না করা পর্যন্ত কিছুই লেখা হবে না।", "data.cancel": "বাতিল", "data.restore.action": "ফিরিয়ে আনুন",
  "data.mode.label": "Backup কীভাবে প্রয়োগ হবে?", "data.mode.merge": "একসাথে মেশান", "data.mode.merge.description": "এই browser-এ যা আছে সব থাকবে। Backup-এ একই item থাকলে backup-এর সংস্করণটি ব্যবহার হবে।", "data.mode.replace": "বদলে দিন", "data.mode.replace.description": "এই সাইটের বর্তমান local data প্রথমে মুছে যাবে, তারপর শুধু backup-এ যা আছে তা restore হবে।",
  "data.restore.mergeAction": "Merge ও restore", "data.restore.replaceAction": "Replace ও restore",
  "data.report.merge": "{imported}টি item restore হয়েছে, {unchanged}টি অপরিবর্তিত আছে।", "data.report.replace": "{imported}টি item restore হয়েছে, {removed}টি মুছে গেছে।",
  "data.selected": "বাছাই করা ফাইল: {name}", "data.empty": "এই browser-এ এখনো কিছু save হয়নি।", "data.downloaded": "{count}টি item নিয়ে backup আপনার device-এ save হয়েছে।",
  "data.error.read": "ফাইলটি পড়া যায়নি। ডাউনলোড করা .json backup বাছুন।", "data.error.invalid": "ফাইলটি বৈধ JSON নয়।", "data.error.version": "Backup-টি সাইটের নতুন সংস্করণে তৈরি, তাই নিরাপদভাবে পড়া যাচ্ছে না।", "data.error.source": "Backup-টি Tools & Games BD-এ তৈরি হয়নি।", "data.error.shape": "Backup-এ প্রত্যাশিত field নেই।", "data.error.namespace": "Backup-এ এমন item আছে যা এই সাইটের নয়। কিছুই বদলানো হয়নি।", "data.error.size": "Backup-টি নিরাপদে restore করার জন্য অনেক বড়।", "data.error.quota": "Browser storage পূর্ণ। কিছুই বদলানো হয়নি।", "data.error.unavailable": "Browser storage ব্যবহার করা যাচ্ছে না—private browsing বাধা দিতে পারে।",
  "common.copy": "কপি করুন", "common.download": "ডাউনলোড", "common.example": "উদাহরণ দেখুন", "common.clear": "মুছুন", "common.reset": "রিসেট", "common.close": "বন্ধ", "common.back": "ফিরে যান", "common.resume": "আবার শুরু করুন", "common.save": "সেভ", "common.loading": "লোড হচ্ছে…", "common.error": "সমস্যা হয়েছে। আবার চেষ্টা করুন।",
  "memory.restore": "আগের input রেস্টোর করুন", "memory.private": "সংবেদনশীল input কখনো মনে রাখা হয় না।", "memory.full": "Browser storage পূর্ণ। এই input মনে রাখা যাবে না।", "memory.forget": "এই input ভুলে যান", "memory.forgotten": "এই টুলের save করা input মুছে গেছে।", "memory.tooLarge": "Input-টি মনে রাখার জন্য অনেক বড়। তবু স্বাভাবিকভাবেই কাজ করবে।",
  "error.title": "এই পেজে অপ্রত্যাশিত সমস্যা হয়েছে।", "error.copy": "কিছুই কোথাও পাঠানো হয়নি এবং আপনার save করা data অপরিবর্তিত আছে। আবার চেষ্টা করুন, বা home workbench-এ ফিরে যান।", "error.details": "টেকনিক্যাল বিবরণ", "error.retry": "আবার চেষ্টা করুন", "error.home": "হোমে যান",
  "notFound.code": "৪০৪ — পাওয়া যায়নি", "notFound.home": "হোম ওয়ার্কবেঞ্চ",
  "game.storageFull": "Browser storage পূর্ণ। গেম চলবে, কিন্তু নতুন progress save নাও হতে পারে।", "game.best": "সেরা", "game.score": "স্কোর", "game.level": "লেভেল", "game.resources": "রিসোর্স", "game.food": "খাবার", "game.lines": "লাইন", "game.next": "পরের", "game.tile": "সর্বোচ্চ টাইল", "game.moves": "চাল", "game.gaps": "ফাঁক", "game.lives": "জীবন", "game.pause": "বিরতি", "game.resume": "চালিয়ে যান", "game.fullscreen": "ফুলস্ক্রিন", "game.exit": "গেমে ফিরুন",
  "control.up": "উপরে", "control.down": "নিচে", "control.left": "বাঁয়ে", "control.right": "ডানে",
  "control.primary": "কাজ", "control.secondary": "দ্বিতীয় কাজ", "control.rotateCw": "ডানে ঘোরান", "control.rotateCcw": "বাঁয়ে ঘোরান",
  "control.drop": "ফেলুন", "control.erase": "মুছুন", "control.letters": "অক্ষর", "control.digits": "সংখ্যা",
  "key.space": "স্পেস", "key.enter": "এন্টার", "key.escape": "Esc", "key.shift": "শিফট", "key.backspace": "ব্যাকস্পেস", "key.delete": "ডিলিট",
  "game.start": "শুরু", "game.restart": "নতুন করে শুরু", "game.playAgain": "আবার খেলুন",
  "game.paused": "বিরতি চলছে", "game.pausedCopy": "গেম থেমে আছে। আবার চালু না করা পর্যন্ত কিছুই নড়বে না।", "game.pausedHidden": "ট্যাব পেছনে চলে যাওয়ায় গেম থেমে গেছে।",
  "game.over": "গেম শেষ", "game.overCopy": "স্কোর সেভ হয়েছে। আরও ভালো করতে আবার খেলুন।", "game.overWithScore": "গেম শেষ। স্কোর {score}, সেরা {best}।",
  "game.readyTitle": "প্রস্তুত", "game.readyCopy": "শুরু করতে স্পেস চাপুন বা Start-এ ট্যাপ করুন।",
  "game.exitFullscreen": "ফুলস্ক্রিন বন্ধ", "game.controls.title": "নিয়ন্ত্রণ", "game.touchControls": "পর্দার নিয়ন্ত্রণ",
  "game.touchHint": "টাচস্ক্রিনে উপরের বোতামগুলো ব্যবহার করুন। দুই ধরনের নিয়ন্ত্রণ ঠিক একই কাজ করে।",
  "game.comingSoon.badge": "আসছে", "game.comingSoon.title": "এই গেমটি এখনও তৈরি হয়নি।",
  "game.comingSoon.copy": "অর্ধেক কাজ করা বোর্ড প্রকাশ করার বদলে, keyboard ও touch দুটোতেই ঠিকঠাক না চলা পর্যন্ত এটি তালিকায় এভাবেই থাকবে। যেগুলোতে খেলা যায় লেখা আছে, সেগুলো সম্পূর্ণ।",
  "games.playableBadge": "খেলা যায়",
  "game.forget": "এই save মুছুন", "game.missing.title": "এই গেমটি ক্যাবিনেটে নেই।", "game.missing.copy": "এই ঠিকানার সঙ্গে কোনো গেম মেলেনি। পুরো তালিকা দেখে অন্য একটি বাছুন।",
  "tool.input": "ইনপুট", "tool.output": "আউটপুট", "tool.run": "চালান", "tool.browserOnly": "শুধু ব্রাউজারে", "tool.privacy": "কোনো input এই browser-এর বাইরে যায় না।",
  "tool.inputLabel": "{name} ইনপুট", "tool.mode.label": "টুল মোড", "tool.mode.default": "ডিফল্ট", "tool.mode.decode": "ডিকোড", "tool.mode.words": "শব্দ", "tool.mode.lines": "লাইন", "tool.mode.desc": "Z থেকে A", "tool.mode.bulk": "একসঙ্গে ×১০", "tool.mode.yaml": "YAML", "tool.mode.xml": "XML", "tool.mode.unescape": "আনএস্কেপ",
  "tool.copied": "ফলাফল ক্লিপবোর্ডে কপি হয়েছে।", "tool.copyFailed": "ক্লিপবোর্ডে পৌঁছানো যায়নি। ফলাফল নির্বাচন করে নিজে কপি করুন।", "tool.downloaded": "ফলাফল আপনার device-এ save হয়েছে।",
  "tool.missing.title": "এই টুলটি এই ড্রয়ারে নেই।", "tool.missing.copy": "এই ঠিকানার সঙ্গে কোনো টুল মেলেনি। ডিরেক্টরিতে সহজ শব্দ দিয়ে খুঁজুন।",
  "tool.unavailable.badge": "এখনো তৈরি হয়নি", "tool.unavailable.title": "টুলটি তালিকায় আছে, কিন্তু এখনো তৈরি হয়নি।", "tool.unavailable.copy": "এটি পরিকল্পনায় আছে। কিছুই কোথাও পাঠানো হয় না এবং আধা-কাজ করা কোনো ফলাফলও দেখানো হয় না, যাতে সত্যি মনে হওয়া ভুল output আপনাকে বিভ্রান্ত না করে।",
  "tool.result.stats": "লাইভ পরিসংখ্যান", "tool.result.preview": "স্যানিটাইজ করা প্রিভিউ HTML", "tool.result.needsInput": "সঙ্গে সঙ্গে browser-only ফলাফল দেখতে একটি input দিন।", "tool.result.notesHint": "আপনার নোট এই device-এর এই browser-এই থাকে।", "tool.result.signaturePresent": "আছে — লোকালি যাচাই করা হয়নি", "tool.result.signatureMissing": "নেই",
  "tool.bmi.underweight": "কম ওজন", "tool.bmi.healthy": "স্বাস্থ্যকর সীমা", "tool.bmi.overweight": "বেশি ওজন", "tool.bmi.obese": "স্থূলতার সীমা",
  "tool.error.generic": "Input পরীক্ষা করে আবার চেষ্টা করুন।", "tool.error.octal": "বৈধ octal mode দিন, যেমন 755।", "tool.error.hex": "৬ অঙ্কের HEX রঙ দিন, যেমন #3264FF।", "tool.error.jwt": "header.payload.signature আকারে token দিন।", "tool.error.number": "স্পেস বা কমা দিয়ে আলাদা করে এক বা দুটি সংখ্যা দিন।",
  "tool.error.math.badChar": "শুধু সংখ্যা, অপারেটর ও পরিচিত function নাম ব্যবহার করা যাবে।", "tool.error.math.badSyntax": "রাশিটি অসম্পূর্ণ অথবা বন্ধনী মেলেনি।", "tool.error.math.unknownName": "অপরিচিত function বা constant নাম।", "tool.error.math.badArgs": "Function-টিতে ভুল সংখ্যক argument দেওয়া হয়েছে।", "tool.error.math.notFinite": "ফলাফলটি সসীম সংখ্যা নয়।", "tool.error.math.tooLong": "রাশিটি অনেক লম্বা।",
  "tool.error.fileTooLarge": "ফাইলটি browser-এ hash করার জন্য অনেক বড় (সর্বোচ্চ ৫০ MB)।", "tool.hash.note": "Hash Web Crypto দিয়ে লোকালেই গণনা হয়। SHA-1 শুধু checksum — password রাখতে কখনো hash ব্যবহার করবেন না।", "tool.file.choose": "ফাইল বাছুন", "tool.file.selected": "বাছাই করা ফাইল: {name} ({size})", "tool.file.hashNote": "Hash গণনার জন্য ফাইল শুধু এই device-এ পড়া হয়। কিছুই আপলোড হয় না।", "tool.file.noFile": "SHA hash লোকালেই গণনা করতে একটি ফাইল বাছুন।", "tool.file.cancel": "ফাইল সরান",
  "home.eyebrow": "ব্যক্তিগত ব্রাউজার ওয়ার্কবেঞ্চ", "home.metaTitle": "দরকারি টুল, অরিজিনাল গেম, কোনো sign-up নেই", "home.titleA": "দরকারি টুলস।", "home.titleB": "অরিজিনাল গেমস।", "home.titleC": "কোনো sign-up নেই।", "home.copy": "কাজ করুন, তৈরি করুন এবং ঠিকঠাক বিরতি নিন—নিজের data ছেড়ে না দিয়ে। প্রতিটি মূল টুল আপনার browser-এই কাজ করে।", "home.tools": "টুলস দেখুন", "home.games": "গেম খেলুন", "home.statTools": "২০০+ টুল", "home.statGames": "৩২ গেম", "home.statFree": "১০০% ফ্রি", "home.statPrivacy": "কোনো sign-up নেই", "home.featured": "ফিচারড ওয়ার্কবেঞ্চ", "home.featuredCopy": "প্রতিদিনের দরকারি একটি টুল দিয়ে শুরু করুন।", "home.categories": "নিজের instrument tray বাছুন", "home.categoriesCopy": "যেভাবে ভাবেন, সেভাবে টুল সাজানো—কোনো server কী collect করতে পারে, তা দিয়ে নয়।", "home.gameKicker": "লোকালেই খেলুন", "home.gamesTitle": "বিরতিটা আরও ভালো হোক।", "home.gamesCopy": "অরিজিনাল browser game। যেগুলোতে খেলা যায় লেখা আছে, প্রতিটি keyboard ও touch দুটোতেই চলে, আর high score শুধু আপনার device-এ সেভ হয়।", "home.aiKicker": "নিজের key ব্যবহার করুন", "home.aiTitle": "AI, যখন আপনি চান।", "home.aiCopy": "নিজের provider key লোকালেই যুক্ত করুন, অথবা ফ্রি browser voice tool ব্যবহার করুন—আমাদের সাইটে কোনো account লাগবে না।", "home.viewAi": "AI টুল দেখুন", "home.viewAll": "সব দেখুন",
  "tools.eyebrow": "টুল ডিরেক্টরি", "tools.title": "পরের shortcut খুঁজে নিন।", "tools.copy": "প্রতিটি টুল local-first, দ্রুত এবং দেখানোর আগে কাজে লাগার জন্য তৈরি।", "tools.all": "সব ক্যাটাগরি", "tools.resultCount": "{count}টি টুল", "tools.empty": "এই খোঁজে কোনো টুল পাওয়া যায়নি। সহজ শব্দ দিয়ে চেষ্টা করুন।", "tools.filterLabel": "ক্যাটাগরি অনুযায়ী টুল ফিল্টার", "tools.resultsHeading": "মিলে যাওয়া টুল",
  "games.eyebrow": "অরিজিনাল ব্রাউজার গেম", "games.title": "দক্ষতার সঙ্গে বিরতি নিন।", "games.copy": "কোনো ad নেই, online lobby নেই, account নেই। যেগুলোতে খেলা যায় লেখা আছে, প্রতিটি keyboard ও touch দুটোতেই চলে।", "games.all": "সব genre", "games.count": "{count}টি গেম", "games.empty": "এই genre-এ কোনো গেম পাওয়া যায়নি।", "games.filterLabel": "Genre অনুযায়ী গেম ফিল্টার",
  "links.eyebrow": "দরকারি লিংক ডিরেক্টরি", "links.title": "হাতের কাছে রাখার মতো নির্ভরযোগ্য জায়গা।", "links.copy": "বাংলাদেশে শেখা, তৈরি, কাজ এবং প্রতিদিনের প্রয়োজনের জন্য বাছাই করা searchable directory।", "links.search": "দরকারি সাইট খুঁজুন…", "links.visit": "সাইটে যান", "links.all": "সব ডিরেক্টরি", "links.empty": "কোনো দরকারি লিংক পাওয়া যায়নি।", "links.filterLabel": "ডিরেক্টরি অনুযায়ী লিংক ফিল্টার",
  "ai.eyebrow": "নিজের API KEY ব্যবহার করুন", "ai.title": "আপনার key। আপনার browser। আপনার সিদ্ধান্ত।", "ai.copy": "এই পেজটি শুধু সেটআপ নির্দেশিকা — এখনো কোনো AI call চলে না। ভবিষ্যতে AI টুল চললে তা আপনার browser ও বেছে নেওয়া provider-এর মধ্যে সরাসরি যাবে। আমরা key proxy, collect বা inspect করি না। ফন্ট Google Fonts থেকে লোড হয়।", "ai.stepsTitle": "ছয়টি সহজ ধাপে সেটআপ", "ai.step1": "Provider-এর লিংকে যান", "ai.step2": "নিজের account-এ sign in করুন", "ai.step3": "একটি API key তৈরি করুন", "ai.step4": "Key copy করুন", "ai.step5": "প্রাসঙ্গিক AI tool-এ paste করুন", "ai.step6": "ব্যস—চাইলে My Data থেকে যেকোনো সময় clear করুন।", "ai.security": "নিরাপত্তা নোট: আপনার key এই browser-এর local storage-এই থাকে। আমরা কখনো পাই না।", "ai.providers": "সুপারিশকৃত provider", "ai.free": "ফ্রি, key ছাড়া voice tool", "ai.speech": "ব্রাউজার স্পিচ টু টেক্সট", "ai.tts": "ব্রাউজার টেক্সট টু স্পিচ", "ai.recorder": "ভয়েস রেকর্ডার",
  "static.about.title": "ইন্টারনেটে কাজে লাগা সময়ের জন্য তৈরি।", "static.about.copy": "Tools & Games BD হলো দৈনন্দিন utility, অরিজিনাল browser game ও দরকারি লিংকের client-side সংগ্রহ। সহজ বিশ্বাসটিই এর ভিত্তি: ভালো tool তার user-কে সম্মান করে।", "static.how.title": "কীভাবে কাজ করে", "static.how.copy": "একটি tool খুলুন, input দিন এবং সঙ্গে সঙ্গে result পান। শেষ হলে copy বা download করুন। সাধারণ tool input, game save এবং পছন্দগুলো কেবল এই device থেকেই restore করা যায়।", "static.privacy.title": "নকশাতেই ব্যক্তিগত।", "static.privacy.copy": "আমরা account system, tracking pixel, analytics বা এমন কোনো server চালাই না যা আপনার tool input পায়। মূল processing আপনার browser-এ হয়। ফন্ট Google Fonts থেকে লোড হয়। ভবিষ্যতে AI টুল এলে তা আপনার browser থেকে provider-এর কাছে সরাসরি যাবে — এখনো কিছুই চলে না।", "static.notFound.title": "এই ওয়ার্কবেঞ্চের ড্রয়ারটি খালি।", "static.notFound.copy": "আপনি যে পেজটি চেয়েছেন, তা এখানে নেই। একটি tool search করুন অথবা home workbench-এ ফিরে যান।",
  "appearance.title": "কাস্টম থিম", "appearance.copy": "পরিচিত developer palette বাছুন, অথবা token ধরে নিজের ব্যক্তিগত theme তৈরি করুন। প্রতিটি পরিবর্তন এই browser-এই থাকে।", "appearance.mode": "অ্যাপিয়ারেন্স", "appearance.use": "এই থিম ব্যবহার করুন", "appearance.edit": "থিম এডিট", "appearance.delete": "থিম মুছুন", "appearance.create": "নিজের থিম তৈরি করুন", "appearance.reset": "রিসেট", "appearance.name": "থিমের নাম", "appearance.namePlaceholder": "যেমন: আমার কোবাল্ট ডেস্ক", "appearance.save": "থিম সেভ করুন", "appearance.export": "থিম এক্সপোর্ট", "appearance.import": "থিম ইমপোর্ট", "appearance.paste": "ক্লিপবোর্ড পেস্ট", "appearance.importPlaceholder": "এখানে ছয়-token theme JSON object পেস্ট করুন…", "appearance.copied": "Theme JSON ক্লিপবোর্ডে কপি হয়েছে।", "appearance.imported": "Theme token editor-এ লোড হয়েছে।", "appearance.invalid": "এটি বৈধ ছয়-token theme JSON object নয়।", "appearance.nameRequired": "সেভ করার আগে custom theme-এর একটি নাম দিন।", "appearance.saved": "আপনার custom theme লোকালি save হয়েছে।", "appearance.defaulted": "Built-in Light theme ফিরেছে এবং custom theme মুছে গেছে।", "appearance.resetDefault": "ডিফল্টে ফিরুন", "settings.title": "সেটিংস", "settings.copy": "ভাষা, থিম ও local data control নিজের পছন্দমতো সাজান।",

  "a11y.skip": "মূল বিষয়বস্তুতে যান", "a11y.home": "Tools & Games BD — হোম", "a11y.mainNav": "মূল নেভিগেশন", "a11y.drawerNav": "সাইট মেনু",
  "a11y.openMenu": "মেনু খুলুন", "a11y.closeMenu": "মেনু বন্ধ করুন", "a11y.searchDrawer": "টুল ও গেম সার্চ", "a11y.themeSwatches": "প্যালেট প্রিভিউ", "a11y.currentTheme": "বর্তমান থিম",
  "a11y.sortLabel": "ফলাফল সাজান", "a11y.viewLabel": "ফলাফলের লেআউট", "a11y.notifications": "নোটিফিকেশন",
  "a11y.switchLanguage": "সাইটের ভাষা ইংরেজিতে বদলান",

  "appearance.eyebrow": "অ্যাপিয়ারেন্স", "appearance.customEyebrow": "কাস্টম", "appearance.system": "সিস্টেমের সাথে মিলিয়ে নিন",
  "appearance.tokenBackground": "ব্যাকগ্রাউন্ড", "appearance.tokenSurface": "সারফেস", "appearance.tokenText": "টেক্সট",
  "appearance.tokenPrimary": "প্রধান অ্যাকসেন্ট", "appearance.tokenSecondary": "দ্বিতীয় অ্যাকসেন্ট", "appearance.tokenBorder": "বর্ডার",
  "appearance.previewLabel": "লাইভ প্রিভিউ", "appearance.previewHeading": "কাজের জিনিস, পরিষ্কার সাজে।",
  "appearance.previewCard": "কম্পোনেন্ট কার্ড", "appearance.previewStrong": "পরিষ্কার টোকেন কাঠামো",
  "appearance.previewInput": "একটি সাজানো ইনপুট", "appearance.previewButton": "প্রধান অ্যাকশন", "appearance.previewLink": "দ্বিতীয় লিংক",
  "appearance.importedName": "ইমপোর্ট করা থিম", "appearance.previewRegion": "যে থিম সম্পাদনা হচ্ছে তার লাইভ প্রিভিউ",

  "home.markWork": "০১ / কাজ", "home.markPlay": "০২ / খেলা", "home.stepTools": "০১ / টুলস", "home.stepSelect": "০২ / বাছাই", "home.stepPlay": "০৩ / লোকালেই খেলুন", "home.stepAi": "০৪ / নিজের KEY ব্যবহার করুন",
  "tools.instrumentTray": "ইনস্ট্রুমেন্ট ট্রে", "settings.eyebrow": "কন্ট্রোল রুম", "settings.dataEyebrow": "ব্যক্তিগত স্টোরেজ", "static.eyebrow": "TOOLS & GAMES BD",

  "status.linksFiltered": "এই ফিল্টারে {count}টি লিংক মিলেছে।",
  "common.clearSearch": "সার্চ মুছুন", "links.newTab": "নতুন ট্যাবে খুলবে",
};

export const translations: Record<Locale, Record<TranslationKey, string>> = { en, bn };

export function interpolate(template: string, values?: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_match, key) => String(values?.[key] ?? `{${key}}`));
}
