import { Cat, CircleDotDashed, Sparkles } from "lucide-react";
import { useSettings } from "@/contexts/AppSettingsContext";
import { Switch } from "@/components/ui/switch";
import type { Locale } from "@/i18n";
import type { PlayfulEffectKey } from "@/lib/playfulEffects";
import "@/playful-settings.css";

const copy = {
  en: { title: "Playful desktop effects", description: "Optional touches for a pointer-based desktop. They remain off on touch devices and whenever you prefer reduced motion.", stored: "Your choices are saved on this device and sync after sign-in.", cat: "Cursor cat", catCopy: "A quiet cat companion follows your mouse.", trail: "Sparkle & bubble trail", trailCopy: "A small, capped trail appears when you click.", buddy: "Floating buddy", buddyCopy: "A compact buddy occasionally offers a gentle hint." },
  bn: { title: "ডেস্কটপের মজার ইফেক্ট", description: "পয়েন্টার-ভিত্তিক ডেস্কটপের জন্য ঐচ্ছিক সাজসজ্জা। টাচ ডিভাইস ও কম মোশন পছন্দ করলে এগুলো স্বয়ংক্রিয়ভাবে বন্ধ থাকে।", stored: "আপনার পছন্দ এই ডিভাইসে সংরক্ষিত থাকে এবং সাইন ইন করলে সিঙ্ক হয়।", cat: "কার্সর বিড়াল", catCopy: "শান্ত একটি বিড়াল আপনার মাউস অনুসরণ করবে।", trail: "ঝিলিক ও বুদবুদ ট্রেইল", trailCopy: "ক্লিক করলে সীমিত ছোট্ট ট্রেইল দেখা যাবে।", buddy: "ভাসমান সহচর", buddyCopy: "ছোট্ট সহচরটি মাঝে মাঝে সহায়ক ইঙ্গিত দেবে।" },
  hi: { title: "मज़ेदार डेस्कटॉप प्रभाव", description: "पॉइंटर वाले डेस्कटॉप के लिए वैकल्पिक प्रभाव। टच डिवाइस और कम गति की पसंद पर ये स्वतः बंद रहते हैं।", stored: "आपकी पसंद इस डिवाइस पर सहेजी जाती है और साइन इन के बाद सिंक होती है।", cat: "कर्सर बिल्ली", catCopy: "एक शांत बिल्ली आपके माउस का अनुसरण करती है।", trail: "चमक और बुलबुला ट्रेल", trailCopy: "क्लिक करने पर छोटा, सीमित ट्रेल दिखता है।", buddy: "फ़्लोटिंग साथी", buddyCopy: "एक छोटा साथी कभी-कभी हल्का संकेत देता है।" },
  ur: { title: "دلچسپ ڈیسک ٹاپ اثرات", description: "پوائنٹر والے ڈیسک ٹاپ کے لیے اختیاری اثرات۔ ٹچ ڈیوائسز اور کم موشن کی پسند میں یہ خود بخود بند رہتے ہیں۔", stored: "آپ کی پسند اس ڈیوائس پر محفوظ رہتی ہے اور سائن ان کے بعد ہم آہنگ ہوتی ہے۔", cat: "کرسر بلی", catCopy: "ایک پرسکون بلی آپ کے ماؤس کی پیروی کرتی ہے۔", trail: "چمک اور ببل ٹریل", trailCopy: "کلک پر چھوٹا، محدود ٹریل ظاہر ہوتا ہے۔", buddy: "تیرتا ساتھی", buddyCopy: "ایک چھوٹا ساتھی کبھی کبھار ہلکا اشارہ دیتا ہے۔" },
  ar: { title: "تأثيرات سطح المكتب المرحة", description: "تأثيرات اختيارية لأجهزة سطح المكتب ذات المؤشر. تبقى متوقفة على الأجهزة اللمسية وعند تفضيل الحركة المخففة.", stored: "تُحفظ اختياراتك على هذا الجهاز وتُزامن بعد تسجيل الدخول.", cat: "قطة المؤشر", catCopy: "قطة هادئة تتبع الفأرة.", trail: "أثر اللمعان والفقاعات", trailCopy: "يظهر أثر صغير ومحدود عند النقر.", buddy: "رفيق عائم", buddyCopy: "رفيق صغير يقدم تلميحًا لطيفًا من حين لآخر." },
  es: { title: "Efectos divertidos de escritorio", description: "Toques opcionales para un escritorio con puntero. Permanecen desactivados en dispositivos táctiles y cuando prefieres menos movimiento.", stored: "Tus elecciones se guardan en este dispositivo y se sincronizan después de iniciar sesión.", cat: "Gato del cursor", catCopy: "Un gato tranquilo sigue tu ratón.", trail: "Rastro de burbujas y destellos", trailCopy: "Al hacer clic aparece un rastro pequeño y limitado.", buddy: "Compañero flotante", buddyCopy: "Un compañero compacto ofrece una pista suave ocasionalmente." },
  fr: { title: "Effets ludiques pour ordinateur", description: "Des touches facultatives pour un ordinateur à pointeur. Elles restent désactivées sur les appareils tactiles et si vous préférez réduire les animations.", stored: "Vos choix sont enregistrés sur cet appareil et synchronisés après connexion.", cat: "Chat du curseur", catCopy: "Un chat discret suit votre souris.", trail: "Traînée d’étincelles et de bulles", trailCopy: "Une petite traînée limitée apparaît au clic.", buddy: "Compagnon flottant", buddyCopy: "Un petit compagnon offre parfois une indication légère." },
  de: { title: "Verspielte Desktop-Effekte", description: "Optionale Akzente für Desktopgeräte mit Zeiger. Auf Touchgeräten und bei reduzierter Bewegung bleiben sie ausgeschaltet.", stored: "Ihre Auswahl wird auf diesem Gerät gespeichert und nach der Anmeldung synchronisiert.", cat: "Cursor-Katze", catCopy: "Eine ruhige Katze folgt Ihrer Maus.", trail: "Glitzer- und Blasenspur", trailCopy: "Beim Klicken erscheint eine kleine, begrenzte Spur.", buddy: "Schwebender Begleiter", buddyCopy: "Ein kompakter Begleiter gibt gelegentlich einen sanften Hinweis." },
} as const;

const effects: { key: PlayfulEffectKey; icon: typeof Cat; name: keyof typeof copy.en; detail: keyof typeof copy.en }[] = [
  { key: "cat", icon: Cat, name: "cat", detail: "catCopy" }, { key: "trail", icon: Sparkles, name: "trail", detail: "trailCopy" }, { key: "buddy", icon: CircleDotDashed, name: "buddy", detail: "buddyCopy" },
];

export function PlayfulSettings() {
  const { language, playfulEffects, setPlayfulEffect } = useSettings();
  const text = copy[language as Locale] ?? copy.en;
  return <section className="settings-panel playful-settings"><div className="section-heading"><span className="icon-orb"><Sparkles /></span><div><h2>{text.title}</h2><p>{text.description}</p></div></div><div className="effect-settings-list">{effects.map(({ key, icon: Icon, name, detail }) => <label key={key} className="effect-setting"><span className="effect-setting-icon"><Icon size={18} /></span><span><strong>{text[name]}</strong><small>{text[detail]}</small></span><Switch checked={playfulEffects[key]} onCheckedChange={(checked) => setPlayfulEffect(key, checked)} aria-label={text[name]} /></label>)}</div><p className="settings-hint">{text.stored}</p></section>;
}
