/** Cobalt Workshop design reminder: the workbench presents input, output and actions as a fast visual loop; every result is local and inspectable. */
import { useEffect, useMemo, useState } from "react";
import { Check, Clipboard, Download, History, Play, RotateCcw, ShieldCheck, TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { type Tool } from "@/data/tools";
import { useToolInputMemory } from "@/hooks/useToolInputMemory";
import { toolPlaceholder, runTool } from "@/lib/toolOperations";
import { useTranslation } from "@/contexts/AppSettingsContext";

const sensitive = new Set(["password-generator", "bcrypt-hash-compare", "encrypt-decrypt-text", "rsa-key-pair-generator", "totp-otp-generator", "secure-token-generator", "basic-auth-header"]);
const needsMode = new Set(["reverse-text", "sort-list", "base64-text", "url-encode-decode", "html-entities", "yaml-json-toml-xml-converter", "random-number-generator", "uuid-generator"]);
export function ToolWorkspace({ tool }: { tool: Tool }) {
  const { t, language } = useTranslation(); const memory = useToolInputMemory(tool.slug, toolPlaceholder(tool.slug)); const [option, setOption] = useState("default"); const [output, setOutput] = useState(() => runTool(tool.slug, memory.input, option)); const [copied, setCopied] = useState(false);
  const title = useMemo(() => tool.name, [tool.name]);
  useEffect(() => { setOutput(runTool(tool.slug, memory.input, option)); }, [memory.input, option, tool.slug]);
  const copy = async () => { await navigator.clipboard.writeText(output.text); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  const download = () => { const file = new Blob([output.text], { type: output.html ? "text/html" : "text/plain" }); const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(file); anchor.download = `${tool.slug}-result.${output.html ? "html" : "txt"}`; anchor.click(); URL.revokeObjectURL(anchor.href); };
  return <section className="workbench"><div className="workbench-header"><div><p className="eyebrow">{language === "bn" ? tool.categoryBn : tool.category}</p><h1>{title}</h1><p>{tool.description.en}<br /><span className="font-bengali">{tool.description.bn}</span></p></div><div className="privacy-chip"><ShieldCheck className="size-4" />{t("tool.browserOnly")}</div></div>{memory.restoreAvailable && <button className="restore-banner" onClick={memory.restore}><History className="size-4" />{t("memory.restore")}</button>}<div className="grid gap-4 lg:grid-cols-[1fr_1fr]"><div className="bench-panel"><div className="bench-label"><span>{t("tool.input")}</span>{needsMode.has(tool.slug) && <select value={option} onChange={(event) => setOption(event.target.value)} aria-label="Tool mode"><option value="default">Default</option><option value="decode">Decode</option><option value="words">Words</option><option value="lines">Lines</option><option value="desc">Z → A</option><option value="bulk">Bulk ×10</option><option value="yaml">YAML</option><option value="xml">XML</option><option value="unescape">Unescape</option></select>}</div><textarea value={memory.input} onChange={(event) => memory.setInput(event.target.value)} className="tool-textarea" spellCheck={false} placeholder={toolPlaceholder(tool.slug)} aria-label={`${tool.name} input`} /><div className="bench-actions"><Button size="sm" onClick={() => setOutput(runTool(tool.slug, memory.input, option))}><Play className="mr-2 size-3.5" />{t("tool.run")}</Button><Button variant="ghost" size="sm" onClick={() => memory.setInput("")}><RotateCcw className="mr-2 size-3.5" />{t("common.clear")}</Button></div></div><div className="bench-panel bench-result"><div className="bench-label"><span>{output.label ?? t("tool.output")}</span><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={copy} aria-label={t("common.copy")}>{copied ? <Check className="size-4 text-emerald-500" /> : <Clipboard className="size-4" />}</Button><Button size="icon" variant="ghost" onClick={download} aria-label={t("common.download")}><Download className="size-4" /></Button></div></div>{output.html ? <div className="tool-html-preview" dangerouslySetInnerHTML={{ __html: output.html }} /> : <pre className="tool-output">{output.text}</pre>}<div className="bench-actions"><Button variant="outline" size="sm" onClick={copy}>{copied ? <Check className="mr-2 size-3.5" /> : <Clipboard className="mr-2 size-3.5" />}{t("common.copy")}</Button><Button variant="outline" size="sm" onClick={download}><Download className="mr-2 size-3.5" />{t("common.download")}</Button></div></div></div>{sensitive.has(tool.slug) ? <p className="tool-note"><ShieldCheck className="size-4" />{t("memory.private")}</p> : memory.storageWarning ? <p className="tool-note tool-note-warning"><TriangleAlert className="size-4" />{t("memory.full")}</p> : <p className="tool-note"><ShieldCheck className="size-4" />{t("tool.privacy")}</p>}</section>;
}
